CI/run-audit-deps:
- DEPS
- package.json
- package-lock.json
- script/audit_deps.py
- "**/Cargo.toml"
- "**/Cargo.lock"

CI/run-network-audit:
- browser/net/*
- chromium_src/net/**/*
- chromium_src/**/*features.cc
- patches/chrome-VERSION.patch

CI/run-upstream-tests:
- browser/about_flags.cc
- chromium_src/**/*features.cc

CI/storybook-url:
- "**/*.ts"
- "**/*.tsx"
- "**/*.svelte"
- "**/*.css"
- "**/*.scss"

feature/web3/wallet:
- android/java/org/chromium/chrome/browser/app/domain/**/*
- android/java/org/chromium/chrome/browser/crypto_wallet/**/*
- browser/hns_wallet/android/**/*
- browser/resources/settings/hns_wallet_page/**/*
- browser/ui/hns_wallet/**/*
- browser/ui/webui/hns_wallet/**/*
- components/hns_wallet/**/*
- components/hns_wallet_ui/**/*

feature/web3/wallet/core:
- browser/hns_wallet/android/**/*
- browser/resources/settings/hns_wallet_page/**/*
- browser/ui/hns_wallet/**/*
- browser/ui/webui/hns_wallet/**/*
- components/hns_wallet/**/*

potential-layer-violation-fixes:
- browser/android/BUILD.gn
- browser/android/preferences/BUILD.gn
- browser/extensions/BUILD.gn
- browser/farbling/BUILD.gn
- browser/gcm_driver/BUILD.gn
- browser/infobars/BUILD.gn
- browser/net/BUILD.gn
- browser/notifications/BUILD.gn
- browser/profiles/BUILD.gn
- browser/renderer_context_menu/BUILD.gn
- browser/tor/BUILD.gn
- browser/ui/BUILD.gn
- browser/ui/bookmark/BUILD.gn
- browser/ui/sidebar/BUILD.gn
- browser/ui/tabs/BUILD.gn
- browser/ui/views/infobars/BUILD.gn
- browser/webcompat_reporter/BUILD.gn
- browser/widevine/BUILD.gn
- components/hns_ads/browser/BUILD.gn
- components/hns_referrals/browser/BUILD.gn
- components/hns_rewards/browser/BUILD.gn
- components/hns_sync/BUILD.gn
- components/hns_webtorrent/browser/BUILD.gn
- components/content_settings/core/browser/BUILD.gn
