/* Copyright (c) 2020 The Hns Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at https://mozilla.org/MPL/2.0/. */

#ifndef HNS_COMPONENTS_HNS_WALLET_BROWSER_HNS_WALLET_CONSTANTS_H_
#define HNS_COMPONENTS_HNS_WALLET_BROWSER_HNS_WALLET_CONSTANTS_H_

#include <string>
#include <vector>

#include "base/no_destructor.h"
#include "hns/components/hns_wallet/common/hns_wallet.mojom.h"
#include "hns/components/hns_wallet/common/hns_wallet_types.h"
#include "hns/components/hns_wallet/common/switches.h"
#include "components/grit/hns_components_strings.h"
#include "ui/base/webui/web_ui_util.h"

namespace hns_wallet {

constexpr char kHnsServicesKeyHeader[] = "x-hns-key";

constexpr uint256_t kDefaultSendEthGasLimit = 21000;
constexpr uint256_t kDefaultERC20TransferGasLimit = 300000;
constexpr uint256_t kDefaultERC721TransferGasLimit = 800000;
constexpr uint256_t kDefaultERC20ApproveGasLimit = 300000;

constexpr int32_t kAutoLockMinutesMin = 1;
constexpr int32_t kAutoLockMinutesMax = 10080;

constexpr int32_t kAssetDiscoveryMinutesPerRequest = 1;

constexpr char kWalletBaseDirectory[] = "HnsWallet";
constexpr char kImageSourceHost[] = "erc-token-images";
constexpr char kRampBaseUrl[] = "https://app.ramp.network";
constexpr char kOffRampEnabledFlows[] = "ONRAMP,OFFRAMP";
constexpr char kOffRampDefaultFlow[] = "OFFRAMP";
constexpr char kRampID[] = "8yxja8782as5essk2myz3bmh4az6gpq4nte9n2gf";
constexpr char kSardineStorefrontBaseURL[] = "https://crypto.sardine.ai";
constexpr char kSardineClientTokensURL[] =
    "https://api.sardine.ai/v1/auth/client-tokens";
constexpr char kTransakURL[] = "https://global.transak.com/";
constexpr char kTransakApiKey[] = "985d14f0-4cf5-4a4c-8917-78107620d3b7";
constexpr char kCoinbaseURL[] = "https://pay.coinbase.com";
constexpr char kCoinbaseAppId[] = "8072ff71-8469-4fef-9404-7c905e2359c9";
constexpr char kSimpleHashUrl[] = "https://api.simplehash.com";
constexpr char kSimpleHashHnsProxyUrl[] =
    "https://simplehash.wallet.hns.com";

constexpr webui::LocalizedString kLocalizedStrings[] = {
    {"hnsWalletNetworkFees", IDS_HNS_WALLET_NETWORK_FEES},
    {"hnsWalletSolanaSysvarRentProgram",
     IDS_HNS_WALLET_SOLANA_SYSVAR_RENT_PROGRAM},
    {"hnsWalletSolanaMetaDataProgram",
     IDS_HNS_WALLET_SOLANA_META_DATA_PROGRAM},
    {"hnsWalletSolanaAssociatedTokenProgram",
     IDS_HNS_WALLET_SOLANA_ASSOCIATED_TOKEN_PROGRAM},
    {"hnsWalletSolanaTokenProgram", IDS_HNS_WALLET_SOLANA_TOKEN_PROGRAM},
    {"hnsWalletTransactionHasFeeEstimatesError",
     IDS_HNS_WALLET_TRANSACTION_HAS_FEE_ESTIMATES_ERROR},
    {"hnsWalletGasFeeLimitLowerThanBaseFeeWarning",
     IDS_HNS_WALLET_GAS_FEE_LIMIT_LOWER_THAN_BASE_FEE_WARNING},
    {"hnsWalletTokenMintAddress", IDS_HNS_WALLET_TOKEN_MINT_ADDRESS},
    {"hnsWalletActivity", IDS_HNS_WALLET_ACTIVITY},
    {"hnsWalletTokenDecimalsIsRequiredError",
     IDS_HNS_WALLET_TOKEN_DECIMALS_IS_REQUIRED_ERROR},
    {"hnsWalletTokenSymbolIsRequiredError",
     IDS_HNS_WALLET_TOKEN_SYMBOL_IS_REQUIRED_ERROR},
    {"hnsWalletInvalidTokenContractAddressError",
     IDS_HNS_WALLET_INVALID_TOKEN_CONTRACT_ADDRESS_ERROR},
    {"hnsWalletTokenNameIsRequiredError",
     IDS_HNS_WALLET_TOKEN_NAME_IS_REQUIRED_ERROR},
    {"hnsWalletNetworkIsRequiredError",
     IDS_HNS_WALLET_NETWORK_IS_REQUIRED_ERROR},
    {"hnsWalletEnterYourPasswordToStartBackup",
     IDS_HNS_WALLET_ENTER_YOUR_PASSWORD_TO_START_BACKUP},
    {"hnsWalletEnterAPassswordToContinue",
     IDS_HNS_WALLET_ENTER_A_PASSSWORD_TO_CONTINUE},
    {"hnsWalletNoTransactionsYetDescription",
     IDS_HNS_WALLET_NO_TRANSACTIONS_YET_DESCRIPTION},
    {"hnsWalletNoTransactionsYet", IDS_HNS_WALLET_NO_TRANSACTIONS_YET},
    {"hnsWalletInvalidMnemonicError", IDS_WALLET_INVALID_MNEMONIC_ERROR},
    {"hnsWalletRecoveryPhraseLengthError",
     IDS_HNS_WALLET_RECOVERY_PHRASE_LENGTH_ERROR},
    {"hnsWalletOrdinalTwentyFourth", IDS_HNS_WALLET_ORDINAL_TWENTY_FOURTH},
    {"hnsWalletOrdinalTwentyThird", IDS_HNS_WALLET_ORDINAL_TWENTY_THIRD},
    {"hnsWalletOrdinalTwentySecond", IDS_HNS_WALLET_ORDINAL_TWENTY_SECOND},
    {"hnsWalletOrdinalTwentyFirst", IDS_HNS_WALLET_ORDINAL_TWENTY_FIRST},
    {"hnsWalletOrdinalTwentieth", IDS_HNS_WALLET_ORDINAL_TWENTIETH},
    {"hnsWalletOrdinalNineteenth", IDS_HNS_WALLET_ORDINAL_NINETEENTH},
    {"hnsWalletOrdinalEighteenth", IDS_HNS_WALLET_ORDINAL_EIGHTEENTH},
    {"hnsWalletOrdinalSeventeenth", IDS_HNS_WALLET_ORDINAL_SEVENTEENTH},
    {"hnsWalletOrdinalSixteenth", IDS_HNS_WALLET_ORDINAL_SIXTEENTH},
    {"hnsWalletOrdinalFifteenth", IDS_HNS_WALLET_ORDINAL_FIFTEENTH},
    {"hnsWalletOrdinalFourteenth", IDS_HNS_WALLET_ORDINAL_FOURTEENTH},
    {"hnsWalletOridinalThirteenth", IDS_HNS_WALLET_ORIDINAL_THIRTEENTH},
    {"hnsWalletOrdinalTwelfth", IDS_HNS_WALLET_ORDINAL_TWELFTH},
    {"hnsWalletOrdinalSuffixOther", IDS_HNS_WALLET_ORDINAL_SUFFIX_OTHER},
    {"hnsWalletOrdinalSuffixFew", IDS_HNS_WALLET_ORDINAL_SUFFIX_FEW},
    {"hnsWalletOrdinalSuffixTwo", IDS_HNS_WALLET_ORDINAL_SUFFIX_TWO},
    {"hnsWalletOrdinalSuffixOne", IDS_HNS_WALLET_ORDINAL_SUFFIX_ONE},
    {"hnsWalletOrdinalEleventh", IDS_HNS_WALLET_ORDINAL_ELEVENTH},
    {"hnsWalletOrdinalTenth", IDS_HNS_WALLET_ORDINAL_TENTH},
    {"hnsWalletOrdinalNinth", IDS_HNS_WALLET_ORDINAL_NINTH},
    {"hnsWalletOrdinalEighth", IDS_HNS_WALLET_ORDINAL_EIGHTH},
    {"hnsWalletOrdinalSeventh", IDS_HNS_WALLET_ORDINAL_SEVENTH},
    {"hnsWalletOrdinalSixth", IDS_HNS_WALLET_ORDINAL_SIXTH},
    {"hnsWalletOrdinalFifth", IDS_HNS_WALLET_ORDINAL_FIFTH},
    {"hnsWalletOrdinalFourth", IDS_HNS_WALLET_ORDINAL_FOURTH},
    {"hnsWalletOrdinalSecond", IDS_HNS_WALLET_ORDINAL_SECOND},
    {"hnsWalletRemoveAccountModalTitle",
     IDS_HNS_WALLET_REMOVE_ACCOUNT_MODAL_TITLE},
    {"hnsWalletViewDecodedMessage", IDS_HNS_WALLET_VIEW_DECODED_MESSAGE},
    {"hnsWalletViewEncodedMessage", IDS_HNS_WALLET_VIEW_ENCODED_MESSAGE},
    {"hnsWalletNonAsciiCharactersInMessageWarning",
     IDS_HNS_WALLET_NON_ASCII_CHARACTERS_IN_MESSAGE_WARNING},
    {"hnsWalletEnterYourPassword", IDS_HNS_WALLET_ENTER_YOUR_PASSWORD},
    {"hnsWalletEnterYourHnsWalletPassword",
     IDS_HNS_WALLET_ENTER_YOUR_HNS_WALLET_PASSWORD},
    {"hnsWalletClickToSwitch", IDS_HNS_WALLET_CLICK_TO_SWITCH},
    {"hnsWalletUnlockNeededToCreateAccount",
     IDS_HNS_WALLET_UNLOCK_NEEDED_TO_CREATE_ACCOUNT},
    {"hnsWalletMultiChain", IDS_HNS_WALLET_MULTI_CHAIN},
    {"hnsWalletPerksBrowserNative", IDS_HNS_WALLET_PERKS_BROWSER_NATIVE},
    {"hnsWalletPerksTokens", IDS_HNS_WALLET_PERKS_TOKENS},
    {"hnsWallet", IDS_HNS_WALLET},
    {"hnsWalletDefiCategory", IDS_HNS_WALLET_DEFI_CATEGORY},
    {"hnsWalletNftCategory", IDS_HNS_WALLET_NFT_CATEGORY},
    {"hnsWalletSearchCategory", IDS_HNS_WALLET_SEARCH_CATEGORY},
    {"hnsWalletDefiButtonText", IDS_HNS_WALLET_DEFI_BUTTON_TEXT},
    {"hnsWalletNftButtonText", IDS_HNS_WALLET_NFT_BUTTON_TEXT},
    {"hnsWalletCompoundName", IDS_HNS_WALLET_COMPOUND_NAME},
    {"hnsWalletCompoundDescription", IDS_HNS_WALLET_COMPOUND_DESCRIPTION},
    {"hnsWalletMakerName", IDS_HNS_WALLET_MAKER_NAME},
    {"hnsWalletMakerDescription", IDS_HNS_WALLET_MAKER_DESCRIPTION},
    {"hnsWalletAaveName", IDS_HNS_WALLET_AAVE_NAME},
    {"hnsWalletAaveDescription", IDS_HNS_WALLET_AAVE_DESCRIPTION},
    {"hnsWalletOpenSeaName", IDS_HNS_WALLET_OPEN_SEA_NAME},
    {"hnsWalletOpenSeaDescription", IDS_HNS_WALLET_OPEN_SEA_DESCRIPTION},
    {"hnsWalletRaribleName", IDS_HNS_WALLET_RARIBLE_NAME},
    {"hnsWalletRaribleDescription", IDS_HNS_WALLET_RARIBLE_DESCRIPTION},
    {"hnsWalletSearchText", IDS_HNS_WALLET_SEARCH_TEXT},
    {"hnsWalletSideNavCrypto", IDS_HNS_WALLET_SIDE_NAV_CRYPTO},
    {"hnsWalletSideNavRewards", IDS_HNS_WALLET_SIDE_NAV_REWARDS},
    {"hnsWalletSideNavCards", IDS_HNS_WALLET_SIDE_NAV_CARDS},
    {"hnsWalletTopNavPortfolio", IDS_HNS_WALLET_TOP_NAV_PORTFOLIO},
    {"hnsWalletTopTabPrices", IDS_HNS_WALLET_TOP_TAB_PRICES},
    {"hnsWalletTopTabApps", IDS_HNS_WALLET_TOP_TAB_APPS},
    {"hnsWalletTopNavNFTS", IDS_HNS_WALLET_TOP_NAV_N_F_T_S},
    {"hnsWalletTopNavAccounts", IDS_HNS_WALLET_TOP_NAV_ACCOUNTS},
    {"hnsWalletTopNavMarket", IDS_HNS_WALLET_TOP_NAV_MARKET},
    {"hnsWalletChartOneHour", IDS_HNS_WALLET_CHART_ONE_HOUR},
    {"hnsWalletChartOneDay", IDS_HNS_WALLET_CHART_ONE_DAY},
    {"hnsWalletChartOneWeek", IDS_HNS_WALLET_CHART_ONE_WEEK},
    {"hnsWalletChartOneMonth", IDS_HNS_WALLET_CHART_ONE_MONTH},
    {"hnsWalletChartThreeMonths", IDS_HNS_WALLET_CHART_THREE_MONTHS},
    {"hnsWalletChartOneYear", IDS_HNS_WALLET_CHART_ONE_YEAR},
    {"hnsWalletChartAllTime", IDS_HNS_WALLET_CHART_ALL_TIME},
    {"hnsWalletChartOneHourAbbr", IDS_HNS_WALLET_CHART_ONE_HOUR_ABBR},
    {"hnsWalletChartOneDayAbbr", IDS_HNS_WALLET_CHART_ONE_DAY_ABBR},
    {"hnsWalletChartOneWeekAbbr", IDS_HNS_WALLET_CHART_ONE_WEEK_ABBR},
    {"hnsWalletChartOneMonthAbbr", IDS_HNS_WALLET_CHART_ONE_MONTH_ABBR},
    {"hnsWalletChartThreeMonthsAbbr",
     IDS_HNS_WALLET_CHART_THREE_MONTHS_ABBR},
    {"hnsWalletChartOneYearAbbr", IDS_HNS_WALLET_CHART_ONE_YEAR_ABBR},
    {"hnsWalletChartAllTimeAbbr", IDS_HNS_WALLET_CHART_ALL_TIME_ABBR},
    {"hnsWalletAddCoin", IDS_HNS_WALLET_ADD_COIN},
    {"hnsWalletBalance", IDS_HNS_WALLET_BALANCE},
    {"hnsWalletPortfolioAssetNetworkDescription",
     IDS_HNS_WALLET_PORTFOLIO_ASSET_NETWORK_DESCRIPTION},
    {"hnsWalletAccounts", IDS_HNS_WALLET_ACCOUNTS},
    {"hnsWalletAccount", IDS_HNS_WALLET_ACCOUNT},
    {"hnsWalletOwner", IDS_HNS_WALLET_OWNER},
    {"hnsWalletTransactions", IDS_HNS_WALLET_TRANSACTIONS},
    {"hnsWalletPrice", IDS_HNS_WALLET_PRICE},
    {"hnsWalletBack", IDS_HNS_WALLET_BACK},
    {"hnsWalletAddAccount", IDS_HNS_WALLET_ADD_ACCOUNT},
    {"hnsWalletPoweredByCoinGecko", IDS_HNS_WALLET_POWERED_BY_COIN_GECKO},
    {"hnsWalletBuy", IDS_HNS_WALLET_BUY},
    {"hnsWalletSend", IDS_HNS_WALLET_SEND},
    {"hnsWalletSwap", IDS_HNS_WALLET_SWAP},
    {"hnsWalletReset", IDS_HNS_WALLET_RESET},
    {"hnsWalletSell", IDS_HNS_WALLET_SELL},
    {"hnsWalletNotEnoughBalance", IDS_HNS_WALLET_NOT_ENOUGH_BALANCE},
    {"hnsWalletSendToken", IDS_HNS_WALLET_SEND_TOKEN},
    {"hnsWalletSendNFT", IDS_HNS_WALLET_SEND_NFT},
    {"hnsWalletSelectToken", IDS_HNS_WALLET_SELECT_TOKEN},
    {"hnsWalletSelectNFT", IDS_HNS_WALLET_SELECT_NFT},
    {"hnsWalletSendTabSelectTokenTitle",
     IDS_HNS_WALLET_SEND_TAB_SELECT_TOKEN_TITLE},
    {"hnsWalletSendTabSelectNFTTitle",
     IDS_HNS_WALLET_SEND_TAB_SELECT_NFT_TITLE},
    {"hnsWalletEnterRecipientAddress",
     IDS_HNS_WALLET_ENTER_RECIPIENT_ADDRESS},
    {"hnsWalletNotEnoughFunds", IDS_HNS_WALLET_NOT_ENOUGH_FUNDS},
    {"hnsWalletSendHalf", IDS_HNS_WALLET_SEND_HALF},
    {"hnsWalletSendMax", IDS_HNS_WALLET_SEND_MAX},
    {"hnsWalletReviewOrder", IDS_HNS_WALLET_REVIEW_ORDER},
    {"hnsWalletReviewSend", IDS_HNS_WALLET_REVIEW_SEND},
    {"hnsWalletNoAvailableTokens", IDS_HNS_WALLET_NO_AVAILIBLE_TOKENS},
    {"hnsWalletSearchTokens", IDS_HNS_WALLET_SEARCH_TOKENS},
    {"hnsWalletSearchNFTs", IDS_HNS_WALLET_SEARCH_NFTS},
    {"hnsWalletBuyNotSupportedTooltip",
     IDS_HNS_WALLET_BUY_NOT_SUPPORTED_TOOLTIP},
    {"hnsWalletSwapNotSupportedTooltip",
     IDS_HNS_WALLET_SWAP_NOT_SUPPORTED_TOOLTIP},
    {"hnsWalletSlippageToleranceWarning",
     IDS_HNS_WALLET_SLIPPAGE_TOLERANCE_WARNING},
    {"hnsWalletSlippageToleranceTitle",
     IDS_HNS_WALLET_SLIPPAGE_TOLERANCE_TITLE},
    {"hnsWalletExpiresInTitle", IDS_HNS_WALLET_EXPIRES_IN_TITLE},
    {"hnsWalletSendPlaceholder", IDS_HNS_WALLET_SEND_PLACEHOLDER},
    {"hnsWalletSendNoURLPlaceholder",
     IDS_HNS_WALLET_SEND_NO_URL_PLACEHOLDER},
    {"hnsWalletSwapDisclaimer", IDS_HNS_WALLET_SWAP_DISCLAIMER},
    {"hnsWalletSwapDisclaimerDescription",
     IDS_HNS_WALLET_SWAP_DISCLAIMER_DESCRIPTION},
    {"hnsWalletJupiterSwapDisclaimerDescription",
     IDS_HNS_WALLET_JUPITER_SWAP_DISCLAIMER_DESCRIPTION},
    {"hnsWalletSwapFeesNotice", IDS_HNS_WALLET_SWAP_FEES_NOTICE},
    {"hnsWalletDecimalPlacesError", IDS_HNS_WALLET_DECIMAL_PLACES_ERROR},
    {"hnsWalletCreateAccountDescription",
     IDS_HNS_WALLET_CREATE_ACCOUNT_DESCRIPTION},
    {"hnsWalletCreateAccountYes", IDS_HNS_WALLET_CREATE_ACCOUNT_YES},
    {"hnsWalletCreateAccountNo", IDS_HNS_WALLET_CREATE_ACCOUNT_NO},
    {"hnsWalletButtonContinue", IDS_HNS_WALLET_BUTTON_CONTINUE},
    {"hnsWalletButtonNext", IDS_HNS_WALLET_BUTTON_NEXT},
    {"hnsWalletButtonGotIt", IDS_HNS_WALLET_BUTTON_GOT_IT},
    {"hnsWalletButtonCopy", IDS_HNS_WALLET_BUTTON_COPY},
    {"hnsWalletButtonCopied", IDS_HNS_WALLET_BUTTON_COPIED},
    {"hnsWalletButtonVerify", IDS_HNS_WALLET_BUTTON_VERIFY},
    {"hnsWalletButtonClose", IDS_HNS_WALLET_BUTTON_CLOSE},
    {"hnsWalletButtonMore", IDS_HNS_WALLET_BUTTON_MORE},
    {"hnsWalletButtonDone", IDS_HNS_WALLET_BUTTON_DONE},
    {"hnsWalletWelcomeTitle", IDS_HNS_WALLET_WELCOME_TITLE},
    {"hnsWalletWelcomeButton", IDS_HNS_WALLET_WELCOME_BUTTON},
    {"hnsWalletWelcomeRestoreButton",
     IDS_HNS_WALLET_WELCOME_RESTORE_BUTTON},
    {"hnsWalletImportExistingWallet",
     IDS_HNS_WALLET_IMPORT_EXISTING_WALLET},
    {"hnsWalletConnectHardwareWallet",
     IDS_HNS_WALLET_IMPORT_CONNECT_HARDWARE_WALLET},
    {"hnsWalletWelcomeDividerText", IDS_HNS_WALLET_WELCOME_DIVIDER_TEXT},
    {"hnsWalletBackupIntroTitle", IDS_HNS_WALLET_BACKUP_INTRO_TITLE},
    {"hnsWalletBackupIntroDescription",
     IDS_HNS_WALLET_BACKUP_INTRO_DESCRIPTION},
    {"hnsWalletBackupIntroTerms", IDS_HNS_WALLET_BACKUP_INTRO_TERMS},
    {"hnsWalletButtonSkip", IDS_HNS_WALLET_BUTTON_SKIP},
    {"hnsWalletButtonCancel", IDS_HNS_WALLET_BUTTON_CANCEL},
    {"hnsWalletButtonSaveChanges", IDS_HNS_WALLET_BUTTON_SAVE_CHANGES},
    {"hnsWalletRecoveryTitle", IDS_HNS_WALLET_RECOVERY_TITLE},
    {"hnsWalletRecoveryDescription", IDS_HNS_WALLET_RECOVERY_DESCRIPTION},
    {"hnsWalletRecoveryWarning1", IDS_HNS_WALLET_RECOVERY_WARNING1},
    {"hnsWalletRecoveryWarning2", IDS_HNS_WALLET_RECOVERY_WARNING2},
    {"hnsWalletRecoveryWarning3", IDS_HNS_WALLET_RECOVERY_WARNING3},
    {"hnsWalletRecoveryTerms", IDS_HNS_WALLET_RECOVERY_TERMS},
    {"hnsWalletVerifyRecoveryTitle", IDS_HNS_WALLET_VERIFY_RECOVERY_TITLE},
    {"hnsWalletVerifyRecoveryDescription",
     IDS_HNS_WALLET_VERIFY_RECOVERY_DESCRIPTION},
    {"hnsWalletVerifyError", IDS_HNS_WALLET_VERIFY_ERROR},
    {"hnsWalletVerifyRecoveryPhraseTitle",
     IDS_HNS_WALLET_VERIFY_RECOVERY_PHRASE_TITLE},
    {"hnsWalletVerifyRecoveryPhraseInstructions",
     IDS_HNS_WALLET_VERIFY_RECOVERY_PHRASE_INSTRUCTIONS},
    {"hnsWalletVerifyPhraseError", IDS_HNS_WALLET_VERIFY_PHRASE_ERROR},
    {"hnsWalletCreatePasswordTitle", IDS_HNS_WALLET_CREATE_PASSWORD_TITLE},
    {"hnsWalletCreatePasswordDescription",
     IDS_HNS_WALLET_CREATE_PASSWORD_DESCRIPTION},
    {"hnsWalletCreatePasswordInput", IDS_HNS_WALLET_CREATE_PASSWORD_INPUT},
    {"hnsWalletConfirmPasswordInput",
     IDS_HNS_WALLET_CONFIRM_PASSWORD_INPUT},
    {"hnsWalletCreatePasswordError", IDS_HNS_WALLET_CREATE_PASSWORD_ERROR},
    {"hnsWalletConfirmPasswordError",
     IDS_HNS_WALLET_CONFIRM_PASSWORD_ERROR},
    {"hnsWalletLockScreenTitle", IDS_HNS_WALLET_LOCK_SCREEN_TITLE},
    {"hnsWalletLockScreenButton", IDS_HNS_WALLET_LOCK_SCREEN_BUTTON},
    {"hnsWalletLockScreenError", IDS_HNS_WALLET_LOCK_SCREEN_ERROR},
    {"hnsWalletUnlockWallet", IDS_HNS_WALLET_UNLOCK_WALLET},
    {"hnsWalletWalletPopupSettings", IDS_HNS_WALLET_WALLET_POPUP_SETTINGS},
    {"hnsWalletWalletPopupLock", IDS_HNS_WALLET_WALLET_POPUP_LOCK},
    {"hnsWalletWalletPopupBackup", IDS_HNS_WALLET_WALLET_POPUP_BACKUP},
    {"hnsWalletWalletPopupConnectedSites",
     IDS_HNS_WALLET_WALLET_POPUP_CONNECTED_SITES},
    {"hnsWalletWalletPopupHideBalances",
     IDS_HNS_WALLET_WALLET_POPUP_HIDE_BALANCES},
    {"hnsWalletWalletPopupShowGraph",
     IDS_HNS_WALLET_WALLET_POPUP_SHOW_GRAPH},
    {"hnsWalletWalletNFTsTab", IDS_HNS_WALLET_WALLET_NFTS_TAB},
    {"hnsWalletBackupWarningText", IDS_HNS_WALLET_BACKUP_WARNING_TEXT},
    {"hnsWalletBackupButton", IDS_HNS_WALLET_BACKUP_BUTTON},
    {"hnsWalletDismissButton", IDS_HNS_WALLET_DISMISS_BUTTON},
    {"hnsWalletDefaultWalletBanner", IDS_HNS_WALLET_DEFAULT_WALLET_BANNER},
    {"hnsWalletRestoreTite", IDS_HNS_WALLET_RESTORE_TITE},
    {"hnsWalletRestoreDescription", IDS_HNS_WALLET_RESTORE_DESCRIPTION},
    {"hnsWalletRestoreError", IDS_HNS_WALLET_RESTORE_ERROR},
    {"hnsWalletRestorePlaceholder", IDS_HNS_WALLET_RESTORE_PLACEHOLDER},
    {"hnsWalletRestoreShowPhrase", IDS_HNS_WALLET_RESTORE_SHOW_PHRASE},
    {"hnsWalletRestoreLegacyCheckBox",
     IDS_HNS_WALLET_RESTORE_LEGACY_CHECK_BOX},
    {"hnsWalletRestoreFormText", IDS_HNS_WALLET_RESTORE_FORM_TEXT},
    {"hnsWalletToolTipCopyToClipboard",
     IDS_HNS_WALLET_TOOL_TIP_COPY_TO_CLIPBOARD},
    {"hnsWalletToolTipCopiedToClipboard",
     IDS_HNS_WALLET_TOOL_TIP_COPIED_TO_CLIPBOARD},
    {"hnsWalletPasteFromClipboard", IDS_HNS_WALLET_PASTE_FROM_CLIPBOARD},
    {"hnsWalletAccountsPrimary", IDS_HNS_WALLET_ACCOUNTS_PRIMARY},
    {"hnsWalletAccountsSecondary", IDS_HNS_WALLET_ACCOUNTS_SECONDARY},
    {"hnsWalletConnectedHardwareWallets",
     IDS_HNS_WALLET_CONNECTED_HARDWARE_WALLETS},
    {"hnsWalletAccountsAssets", IDS_HNS_WALLET_ACCOUNTS_ASSETS},
    {"hnsWalletAccountsEditVisibleAssets",
     IDS_HNS_WALLET_ACCOUNTS_EDIT_VISIBLE_ASSETS},
    {"hnsWalletAccountBalance", IDS_HNS_WALLET_ACCOUNT_BALANCE},
    {"hnsWalletAddAccountCreate", IDS_HNS_WALLET_ADD_ACCOUNT_CREATE},
    {"hnsWalletCreateAccount", IDS_HNS_WALLET_CREATE_ACCOUNT},
    {"hnsWalletCreateAccountButton", IDS_HNS_WALLET_CREATE_ACCOUNT_BUTTON},
    {"hnsWalletCreateAccountImportAccount",
     IDS_HNS_WALLET_CREATE_ACCOUNT_IMPORT_ACCOUNT},
    {"hnsWalletCreateAccountTitle", IDS_HNS_WALLET_CREATE_ACCOUNT_TITLE},
    {"hnsWalletCreateAccountEthereumDescription",
     IDS_HNS_WALLET_CREATE_ACCOUNT_ETHEREUM_DESCRIPTION},
    {"hnsWalletCreateAccountSolanaDescription",
     IDS_HNS_WALLET_CREATE_ACCOUNT_SOLANA_DESCRIPTION},
    {"hnsWalletCreateAccountFilecoinDescription",
     IDS_HNS_WALLET_CREATE_ACCOUNT_FILECOIN_DESCRIPTION},
    {"hnsWalletCreateAccountBitcoinDescription",
     IDS_HNS_WALLET_CREATE_ACCOUNT_BITCOIN_DESCRIPTION},
    {"hnsWalletFilecoinPrivateKeyProtocol",
     IDS_HNS_WALLET_FILECOIN_PRIVATE_KEY_PROTOCOL},
    {"hnsWalletAddAccountImport", IDS_HNS_WALLET_ADD_ACCOUNT_IMPORT},
    {"hnsWalletAddAccountImportHardware",
     IDS_HNS_WALLET_ADD_ACCOUNT_IMPORT_HARDWARE},
    {"hnsWalletAddAccountHardware", IDS_HNS_WALLET_ADD_ACCOUNT_HARDWARE},
    {"hnsWalletAddAccountConnect", IDS_HNS_WALLET_ADD_ACCOUNT_CONNECT},
    {"hnsWalletAddAccountPlaceholder",
     IDS_HNS_WALLET_ADD_ACCOUNT_PLACEHOLDER},
    {"hnsWalletImportAccountDisclaimer",
     IDS_HNS_WALLET_IMPORT_ACCOUNT_DISCLAIMER},
    {"hnsWalletImportAccountPlaceholder",
     IDS_HNS_WALLET_IMPORT_ACCOUNT_PLACEHOLDER},
    {"hnsWalletImportAccountKey", IDS_HNS_WALLET_IMPORT_ACCOUNT_KEY},
    {"hnsWalletImportAccountFile", IDS_HNS_WALLET_IMPORT_ACCOUNT_FILE},
    {"hnsWalletImportAccountUploadButton",
     IDS_HNS_WALLET_IMPORT_ACCOUNT_UPLOAD_BUTTON},
    {"hnsWalletImportAccountUploadPlaceholder",
     IDS_HNS_WALLET_IMPORT_ACCOUNT_UPLOAD_PLACEHOLDER},
    {"hnsWalletImportAccountError", IDS_HNS_WALLET_IMPORT_ACCOUNT_ERROR},
    {"hnsWalletImportAccount", IDS_HNS_WALLET_IMPORT_ACCOUNT},
    {"hnsWalletConnectHardwareTitle",
     IDS_HNS_WALLET_CONNECT_HARDWARE_TITLE},
    {"hnsWalletConnectHardwareInfo1",
     IDS_HNS_WALLET_CONNECT_HARDWARE_INFO1},
    {"hnsWalletConnectHardwareInfo2",
     IDS_HNS_WALLET_CONNECT_HARDWARE_INFO2},
    {"hnsWalletConnectHardwareWrongApplicationUserHint",
     IDS_HNS_WALLET_CONNECT_HARDWARE_WRONG_APPLICATION_USER_HINT},
    {"hnsWalletConnectHardwareTrezor",
     IDS_HNS_WALLET_CONNECT_HARDWARE_TREZOR},
    {"hnsWalletConnectHardwareLedger",
     IDS_HNS_WALLET_CONNECT_HARDWARE_LEDGER},
    {"hnsWalletConnectHardwareAuthorizationNeeded",
     IDS_HNS_WALLET_CONNECT_HARDWARE_AUTHORIZATION_NEEDED},
    {"hnsWalletConnectingHardwareWallet",
     IDS_HNS_WALLET_CONNECTING_HARDWARE_WALLET},
    {"hnsWalletAddCheckedAccountsHardwareWallet",
     IDS_HNS_WALLET_ADD_CHECKED_ACCOUNTS_HARDWARE_WALLET},
    {"hnsWalletLoadMoreAccountsHardwareWallet",
     IDS_HNS_WALLET_LOAD_MORE_ACCOUNTS_HARDWARE_WALLET},
    {"hnsWalletLoadingMoreAccountsHardwareWallet",
     IDS_HNS_WALLET_LOADING_MORE_ACCOUNTS_HARDWARE_WALLET},
    {"hnsWalletSearchScannedAccounts",
     IDS_HNS_WALLET_SEARCH_SCANNED_ACCOUNTS},
    {"hnsWalletSwitchHDPathTextHardwareWallet",
     IDS_HNS_WALLET_SWITCH_H_D_PATH_TEXT_HARDWARE_WALLET},
    {"hnsWalletLedgerLiveDerivationPath",
     IDS_HNS_WALLET_LEDGER_LIVE_DERIVATION_PATH},
    {"hnsWalletLedgerLegacyDerivationPath",
     IDS_HNS_WALLET_LEDGER_LEGACY_DERIVATION_PATH},
    {"hnsWalletConnectHardwareSearchNothingFound",
     IDS_HNS_WALLET_CONNECT_HARDWARE_SEARCH_NOTHING_FOUND},
    {"hnsWalletUnknownInternalError",
     IDS_HNS_WALLET_UNKNOWN_INTERNAL_ERROR},
    {"hnsWalletAccountSettingsDetails",
     IDS_HNS_WALLET_ACCOUNT_SETTINGS_DETAILS},
    {"hnsWalletAccountSettingsWatchlist",
     IDS_HNS_WALLET_ACCOUNT_SETTINGS_WATCHLIST},
    {"hnsWalletAccountSettingsPrivateKey",
     IDS_HNS_WALLET_ACCOUNT_SETTINGS_PRIVATE_KEY},
    {"hnsWalletAccountSettingsSave", IDS_HNS_WALLET_ACCOUNT_SETTINGS_SAVE},
    {"hnsWalletAccountSettingsRemove",
     IDS_HNS_WALLET_ACCOUNT_SETTINGS_REMOVE},
    {"hnsWalletWatchlistAddCustomAsset",
     IDS_HNS_WALLET_WATCHLIST_ADD_CUSTOM_ASSET},
    {"hnsWalletWatchListTokenName", IDS_HNS_WALLET_WATCH_LIST_TOKEN_NAME},
    {"hnsWalletWatchListTokenAddress",
     IDS_HNS_WALLET_WATCH_LIST_TOKEN_ADDRESS},
    {"hnsWalletWatchListTokenSymbol",
     IDS_HNS_WALLET_WATCH_LIST_TOKEN_SYMBOL},
    {"hnsWalletWatchListTokenDecimals",
     IDS_HNS_WALLET_WATCH_LIST_TOKEN_DECIMALS},
    {"hnsWalletWatchListAdd", IDS_HNS_WALLET_WATCH_LIST_ADD},
    {"hnsWalletWatchListDoneButton", IDS_HNS_WALLET_WATCH_LIST_DONE_BUTTON},
    {"hnsWalletWatchListNoAsset", IDS_HNS_WALLET_WATCH_LIST_NO_ASSET},
    {"hnsWalletWatchListSearchPlaceholder",
     IDS_HNS_WALLET_WATCH_LIST_SEARCH_PLACEHOLDER},
    {"hnsWalletWatchListError", IDS_HNS_WALLET_WATCH_LIST_ERROR},
    {"hnsWalletCustomTokenExistsError",
     IDS_HNS_WALLET_CUSTOM_TOKEN_EXISTS_ERROR},
    {"hnsWalletWatchListTokenId", IDS_HNS_WALLET_WATCH_LIST_TOKEN_ID},
    {"hnsWalletWatchListTokenIdError",
     IDS_HNS_WALLET_WATCH_LIST_TOKEN_ID_ERROR},
    {"hnsWalletWatchListAdvanced", IDS_HNS_WALLET_WATCH_LIST_ADVANCED},
    {"hnsWalletWatchListCoingeckoId",
     IDS_HNS_WALLET_WATCH_LIST_COINGECKO_ID},
    {"hnsWalletIconURL", IDS_HNS_WALLET_ICON_URL},
    {"hnsWalletAddAsset", IDS_HNS_WALLET_ADD_ASSET},
    {"hnsWalletAccountsExport", IDS_HNS_WALLET_ACCOUNTS_EXPORT},
    {"hnsWalletAccountsDeposit", IDS_HNS_WALLET_ACCOUNTS_DEPOSIT},
    {"hnsWalletAccountsRemove", IDS_HNS_WALLET_ACCOUNTS_REMOVE},
    {"hnsWalletNoAvailableAssets", IDS_HNS_WALLET_NO_AVAILABLE_ASSETS},
    {"hnsWalletNoAvailableAssetsDescription",
     IDS_HNS_WALLET_NO_AVAILABLE_ASSETS_DESCRIPTION},
    {"hnsWalletAccountSettingsDisclaimer",
     IDS_HNS_WALLET_ACCOUNT_SETTINGS_DISCLAIMER},
    {"hnsWalletFilExportPrivateKeyFormatDescription",
     IDS_HNS_WALLET_FIL_EXPORT_PRIVATE_KEY_FORMAT_DESCRIPTION},
    {"hnsWalletFilImportPrivateKeyFormatDescription",
     IDS_HNS_WALLET_FIL_IMPORT_PRIVATE_KEY_FORMAT_DESCRIPTION},
    {"hnsWalletAccountSettingsShowKey",
     IDS_HNS_WALLET_ACCOUNT_SETTINGS_SHOW_KEY},
    {"hnsWalletAccountSettingsHideKey",
     IDS_HNS_WALLET_ACCOUNT_SETTINGS_HIDE_KEY},
    {"hnsWalletAccountSettingsUpdateError",
     IDS_HNS_WALLET_ACCOUNT_SETTINGS_UPDATE_ERROR},
    {"hnsWalletPreset25", IDS_HNS_WALLET_PRESET25},
    {"hnsWalletPreset50", IDS_HNS_WALLET_PRESET50},
    {"hnsWalletPreset75", IDS_HNS_WALLET_PRESET75},
    {"hnsWalletPreset100", IDS_HNS_WALLET_PRESET100},
    {"hnsWalletUnsupportedNetwork", IDS_HNS_WALLET_UNSUPPORTED_NETWORK},
    {"hnsWalletNetworkETH", IDS_HNS_WALLET_NETWORK_E_T_H},
    {"hnsWalletNetworkMain", IDS_HNS_WALLET_NETWORK_MAIN},
    {"hnsWalletNetworkTest", IDS_HNS_WALLET_NETWORK_TEST},
    {"hnsWalletNetworkGoerli", IDS_HNS_WALLET_NETWORK_GOERLI},
    {"hnsWalletNetworkSepolia", IDS_HNS_WALLET_NETWORK_SEPOLIA},
    {"hnsWalletNetworkBinance", IDS_HNS_WALLET_NETWORK_BINANCE},
    {"hnsWalletNetworkBinanceAbbr", IDS_HNS_WALLET_NETWORK_BINANCE_ABBR},
    {"hnsWalletNetworkLocalhost", IDS_HNS_WALLET_NETWORK_LOCALHOST},
    {"hnsWalletSelectAccount", IDS_HNS_WALLET_SELECT_ACCOUNT},
    {"hnsWalletSearchAccount", IDS_HNS_WALLET_SEARCH_ACCOUNT},
    {"hnsWalletSelectNetwork", IDS_HNS_WALLET_SELECT_NETWORK},
    {"hnsWalletSelectAsset", IDS_HNS_WALLET_SELECT_ASSET},
    {"hnsWalletSearchAsset", IDS_HNS_WALLET_SEARCH_ASSET},
    {"hnsWalletSwapFrom", IDS_HNS_WALLET_SWAP_FROM},
    {"hnsWalletSwapTo", IDS_HNS_WALLET_SWAP_TO},
    {"hnsWalletSwapEstimate", IDS_HNS_WALLET_SWAP_ESTIMATE},
    {"hnsWalletSwapMarket", IDS_HNS_WALLET_SWAP_MARKET},
    {"hnsWalletSwapLimit", IDS_HNS_WALLET_SWAP_LIMIT},
    {"hnsWalletSwapPriceIn", IDS_HNS_WALLET_SWAP_PRICE_IN},
    {"hnsWalletBuyTitle", IDS_HNS_WALLET_BUY_TITLE},
    {"hnsWalletBuyDescription", IDS_HNS_WALLET_BUY_DESCRIPTION},
    {"hnsWalletBuyContinueButton", IDS_HNS_WALLET_BUY_CONTINUE_BUTTON},
    {"hnsWalletSignTransactionTitle",
     IDS_HNS_WALLET_SIGN_TRANSACTION_TITLE},
    {"hnsWalletSignWarning", IDS_HNS_WALLET_SIGN_WARNING},
    {"hnsWalletSignWarningTitle", IDS_HNS_WALLET_SIGN_WARNING_TITLE},
    {"hnsWalletSignTransactionMessageTitle",
     IDS_HNS_WALLET_SIGN_TRANSACTION_MESSAGE_TITLE},
    {"hnsWalletSignTransactionEIP712MessageDomain",
     IDS_HNS_WALLET_SIGN_TRANSACTION_EIP712_MESSAGE_DOMAIN},
    {"hnsWalletSignTransactionEIP712MessageTitle",
     IDS_HNS_WALLET_SIGN_TRANSACTION_EIP712_MESSAGE_TITLE},
    {"hnsWalletSignTransactionButton",
     IDS_HNS_WALLET_SIGN_TRANSACTION_BUTTON},
    {"hnsWalletProvideEncryptionKeyTitle",
     IDS_HNS_WALLET_PROVIDE_ENCRYPTION_KEY_TITLE},
    {"hnsWalletProvideEncryptionKeyDescription",
     IDS_HNS_WALLET_PROVIDE_ENCRYPTION_KEY_DESCRIPTION},
    {"hnsWalletProvideEncryptionKeyButton",
     IDS_HNS_WALLET_PROVIDE_ENCRYPTION_KEY_BUTTON},
    {"hnsWalletReadEncryptedMessageTitle",
     IDS_HNS_WALLET_READ_ENCRYPTED_MESSAGE_TITLE},
    {"hnsWalletReadEncryptedMessageDecryptButton",
     IDS_HNS_WALLET_READ_ENCRYPTED_MESSAGE_DECRYPT_BUTTON},
    {"hnsWalletReadEncryptedMessageButton",
     IDS_HNS_WALLET_READ_ENCRYPTED_MESSAGE_BUTTON},
    {"hnsWalletAllowSpendTitle", IDS_HNS_WALLET_ALLOW_SPEND_TITLE},
    {"hnsWalletAllowSpendDescription",
     IDS_HNS_WALLET_ALLOW_SPEND_DESCRIPTION},
    {"hnsWalletAllowSpendBoxTitle", IDS_HNS_WALLET_ALLOW_SPEND_BOX_TITLE},
    {"hnsWalletAllowSpendTransactionFee",
     IDS_HNS_WALLET_ALLOW_SPEND_TRANSACTION_FEE},
    {"hnsWalletAllowSpendEditButton",
     IDS_HNS_WALLET_ALLOW_SPEND_EDIT_BUTTON},
    {"hnsWalletAllowSpendDetailsButton",
     IDS_HNS_WALLET_ALLOW_SPEND_DETAILS_BUTTON},
    {"hnsWalletAllowSpendRejectButton",
     IDS_HNS_WALLET_ALLOW_SPEND_REJECT_BUTTON},
    {"hnsWalletAllowSpendConfirmButton",
     IDS_HNS_WALLET_ALLOW_SPEND_CONFIRM_BUTTON},
    {"hnsWalletAllowSpendCurrentAllowance",
     IDS_HNS_WALLET_ALLOW_SPEND_CURRENT_ALLOWANCE},
    {"hnsWalletAllowSpendProposedAllowance",
     IDS_HNS_WALLET_ALLOW_SPEND_PROPOSED_ALLOWANCE},
    {"hnsWalletAllowSpendUnlimitedWarningTitle",
     IDS_HNS_WALLET_ALLOW_SPEND_UNLIMITED_WARNING_TITLE},
    {"hnsWalletAllowAddNetworkTitle",
     IDS_HNS_WALLET_ALLOW_ADD_NETWORK_TITLE},
    {"hnsWalletAllowChangeNetworkTitle",
     IDS_HNS_WALLET_ALLOW_CHANGE_NETWORK_TITLE},
    {"hnsWalletAllowChangeNetworkDescription",
     IDS_HNS_WALLET_ALLOW_CHANGE_NETWORK_DESCRIPTION},
    {"hnsWalletAllowChangeNetworkButton",
     IDS_HNS_WALLET_ALLOW_CHANGE_NETWORK_BUTTON},
    {"hnsWalletAllowAddNetworkDescription",
     IDS_HNS_WALLET_ALLOW_ADD_NETWORK_DESCRIPTION},
    {"hnsWalletAllowAddNetworkLearnMoreButton",
     IDS_HNS_WALLET_ALLOW_ADD_NETWORK_LEARN_MORE_BUTTON},
    {"hnsWalletAllowAddNetworkName", IDS_HNS_WALLET_ALLOW_ADD_NETWORK_NAME},
    {"hnsWalletAllowAddNetworkUrl", IDS_HNS_WALLET_ALLOW_ADD_NETWORK_URL},
    {"hnsWalletAllowAddNetworkDetailsButton",
     IDS_HNS_WALLET_ALLOW_ADD_NETWORK_DETAILS_BUTTON},
    {"hnsWalletAllowAddNetworkButton",
     IDS_HNS_WALLET_ALLOW_ADD_NETWORK_BUTTON},
    {"hnsWalletAllowAddNetworkChainID",
     IDS_HNS_WALLET_ALLOW_ADD_NETWORK_CHAIN_I_D},
    {"hnsWalletAllowAddNetworkCurrencySymbol",
     IDS_HNS_WALLET_ALLOW_ADD_NETWORK_CURRENCY_SYMBOL},
    {"hnsWalletAllowAddNetworkExplorer",
     IDS_HNS_WALLET_ALLOW_ADD_NETWORK_EXPLORER},
    {"hnsWalletAllowAddNetworkNetworkPanelTitle",
     IDS_HNS_WALLET_ALLOW_ADD_NETWORK_PANEL_TITLE},
    {"hnsWalletAllowAddNetworkDetailsPanelTitle",
     IDS_HNS_WALLET_ALLOW_ADD_DETAILS_PANEL_TITLE},
    {"hnsWalletConfirmTransactionTotal",
     IDS_HNS_WALLET_CONFIRM_TRANSACTION_TOTAL},
    {"hnsWalletConfirmTransactionGasFee",
     IDS_HNS_WALLET_CONFIRM_TRANSACTION_GAS_FEE},
    {"hnsWalletConfirmTransactionTransactionFee",
     IDS_HNS_WALLET_CONFIRM_TRANSACTION_TRANSACTION_FEE},
    {"hnsWalletConfirmTransactionBid",
     IDS_HNS_WALLET_CONFIRM_TRANSACTION_BID},
    {"hnsWalletConfirmTransactionAmountGas",
     IDS_HNS_WALLET_CONFIRM_TRANSACTION_AMOUNT_GAS},
    {"hnsWalletConfirmTransactionAmountFee",
     IDS_HNS_WALLET_CONFIRM_TRANSACTION_AMOUNT_FEE},
    {"hnsWalletConfirmTransactionNoData",
     IDS_HNS_WALLET_CONFIRM_TRANSACTION_NO_DATA},
    {"hnsWalletConfirmTransactionNext",
     IDS_HNS_WALLET_CONFIRM_TRANSACTION_NEXT},
    {"hnsWalletConfirmTransactionFrist",
     IDS_HNS_WALLET_CONFIRM_TRANSACTION_FRIST},
    {"hnsWalletConfirmTransactions", IDS_HNS_WALLET_CONFIRM_TRANSACTIONS},
    {"hnsWalletConfirmTransactionAccountCreationFee",
     IDS_HNS_WALLET_CONFIRM_TRANSACTION_ACCOUNT_CREATION_FEE},
    {"hnsWalletTransactionGasLimit", IDS_HNS_WALLET_TRANSACTION_GAS_LIMIT},
    {"hnsWalletTransactionGasPremium",
     IDS_HNS_WALLET_TRANSACTION_GAS_PREMIUM},
    {"hnsWalletTransactionGasFeeCap",
     IDS_HNS_WALLET_TRANSACTION_GAS_FEE_CAP},
    {"hnsWalletPanelTitle", IDS_HNS_WALLET_PANEL_TITLE},
    {"hnsWalletPanelConnected", IDS_HNS_WALLET_PANEL_CONNECTED},
    {"hnsWalletSitePermissionsAccounts",
     IDS_HNS_WALLET_SITE_PERMISSIONS_ACCOUNTS},
    {"hnsWalletSitePermissionsTitle",
     IDS_HNS_WALLET_SITE_PERMISSIONS_TITLE},
    {"hnsWalletSitePermissionsDisconnect",
     IDS_HNS_WALLET_SITE_PERMISSIONS_DISCONNECT},
    {"hnsWalletSitePermissionsSwitch",
     IDS_HNS_WALLET_SITE_PERMISSIONS_SWITCH},
    {"hnsWalletSitePermissionsTrust",
     IDS_HNS_WALLET_SITE_PERMISSIONS_TRUST},
    {"hnsWalletSitePermissionsRevoke",
     IDS_HNS_WALLET_SITE_PERMISSIONS_REVOKE},
    {"hnsWalletChangeNetwork", IDS_HNS_WALLET_CHANGE_NETWORK},
    {"hnsWalletChangeAccount", IDS_HNS_WALLET_CHANGE_ACCOUNT},
    {"hnsWalletActive", IDS_HNS_WALLET_ACTIVE},
    {"hnsWalletNotConnected", IDS_HNS_WALLET_NOT_CONNECTED},
    {"hnsWalletConnectedAccounts", IDS_HNS_WALLET_CONNECTED_ACCOUNTS},
    {"hnsWalletAvailableAccounts", IDS_HNS_WALLET_AVAILABLE_ACCOUNTS},
    {"hnsWalletSitePermissionsNewAccount",
     IDS_HNS_WALLET_SITE_PERMISSIONS_NEW_ACCOUNT},
    {"hnsWalletPanelNotConnected", IDS_HNS_WALLET_PANEL_NOT_CONNECTED},
    {"hnsWalletPanelViewAccountAssets",
     IDS_HNS_WALLET_PANEL_VIEW_ACCOUNT_ASSETS},
    {"hnsWalletAssetsPanelTitle", IDS_HNS_WALLET_ASSETS_PANEL_TITLE},
    {"hnsWalletPanelDisconnected", IDS_HNS_WALLET_PANEL_DISCONNECTED},
    {"hnsWalletPanelBlocked", IDS_HNS_WALLET_PANEL_BLOCKED},
    {"hnsWalletTitle", IDS_HNS_WALLET_TITLE},
    {"hnsWalletWelcomePanelDescription",
     IDS_HNS_WALLET_WELCOME_PANEL_DESCRIPTION},
    {"hnsWalletLearnMore", IDS_HNS_WALLET_LEARN_MORE},
    {"hnsWalletTransactionDetailBoxFunction",
     IDS_HNS_WALLET_TRANSACTION_DETAIL_BOX_FUNCTION},
    {"hnsWalletTransactionDetailBoxHex",
     IDS_HNS_WALLET_TRANSACTION_DETAIL_BOX_HEX},
    {"hnsWalletTransactionDetailBoxBytes",
     IDS_HNS_WALLET_TRANSACTION_DETAIL_BOX_BYTES},
    {"hnsWalletConnectWithSiteNext", IDS_HNS_WALLET_CONNECT_WITH_SITE_NEXT},
    {"hnsWalletConnectWallet", IDS_HNS_WALLET_CONNECT_WALLET},
    {"hnsWalletConnectWithSite", IDS_HNS_WALLET_CONNECT_WITH_SITE},
    {"hnsWalletConnectPermittedLabel",
     IDS_HNS_WALLET_CONNECT_PERMITTED_LABEL},
    {"hnsWalletConnectNotPermittedLabel",
     IDS_HNS_WALLET_CONNECT_NOT_PERMITTED_LABEL},
    {"hnsWalletConnectPermissionBalanceAndActivity",
     IDS_HNS_WALLET_CONNECT_PERMISSION_BALANCE_AND_ACTIVITY},
    {"hnsWalletConnectPermissionRequestApproval",
     IDS_HNS_WALLET_CONNECT_PERMISSION_REQUEST_APPROVAL},
    {"hnsWalletConnectPermissionAddress",
     IDS_HNS_WALLET_CONNECT_PERMISSION_ADDRESS},
    {"hnsWalletConnectPermissionMoveFunds",
     IDS_HNS_WALLET_CONNECT_PERMISSION_MOVE_FUNDS},
    {"hnsWalletConnectTrustWarning", IDS_HNS_WALLET_CONNECT_TRUST_WARNING},
    {"hnsWalletPermissionDuration", IDS_HNS_WALLET_PERMISSION_DURATION},
    {"hnsWalletPermissionUntilClose",
     IDS_HNS_WALLET_PERMISSION_UNTIL_CLOSE},
    {"hnsWalletPermissionOneDay", IDS_HNS_WALLET_PERMISSION_ONE_DAY},
    {"hnsWalletPermissionOneWeek", IDS_HNS_WALLET_PERMISSION_ONE_WEEK},
    {"hnsWalletPermissionForever", IDS_HNS_WALLET_PERMISSION_FOREVER},
    {"hnsWalletCryptoWalletsDetected",
     IDS_HNS_WALLET_CRYPTO_WALLETS_DETECTED},
    {"hnsWalletCryptoWalletsDescriptionTwo",
     IDS_HNS_WALLET_CRYPTO_WALLETS_DESCRIPTION_TWO},
    {"hnsWalletImportHnsLegacyDescription",
     IDS_HNS_WALLET_IMPORT_HNS_LEGACY_DESCRIPTION},
    {"hnsWalletImportHnsLegacyInput",
     IDS_HNS_WALLET_IMPORT_HNS_LEGACY_INPUT},
    {"hnsWalletConnectHardwarePanelConnected",
     IDS_HNS_WALLET_CONNECT_HARDWARE_PANEL_CONNECTED},
    {"hnsWalletConnectHardwarePanelDisconnected",
     IDS_HNS_WALLET_CONNECT_HARDWARE_PANEL_DISCONNECTED},
    {"hnsWalletConnectHardwarePanelInstructions",
     IDS_HNS_WALLET_CONNECT_HARDWARE_PANEL_INSTRUCTIONS},
    {"hnsWalletConnectHardwarePanelConnect",
     IDS_HNS_WALLET_CONNECT_HARDWARE_PANEL_CONNECT},
    {"hnsWalletConnectHardwarePanelConfirmation",
     IDS_HNS_WALLET_CONNECT_HARDWARE_PANEL_CONFIRMATION},
    {"hnsWalletConnectHardwarePanelOpenApp",
     IDS_HNS_WALLET_CONNECT_HARDWARE_PANEL_OPEN_APP},
    {"hnsWalletTransactionSent", IDS_HNS_WALLET_TRANSACTION_SENT},
    {"hnsWalletTransactionReceived", IDS_HNS_WALLET_TRANSACTION_RECEIVED},
    {"hnsWalletTransactionExplorerMissing",
     IDS_HNS_WALLET_TRANSACTION_EXPLORER_MISSING},
    {"hnsWalletTransactionExplorer", IDS_HNS_WALLET_TRANSACTION_EXPLORER},
    {"hnsWalletTransactionCopyHash", IDS_HNS_WALLET_TRANSACTION_COPY_HASH},
    {"hnsWalletTransactionSpeedup", IDS_HNS_WALLET_TRANSACTION_SPEEDUP},
    {"hnsWalletTransactionCancel", IDS_HNS_WALLET_TRANSACTION_CANCEL},
    {"hnsWalletTransactionRetry", IDS_HNS_WALLET_TRANSACTION_RETRY},
    {"hnsWalletTransactionStatusUnapproved",
     IDS_HNS_WALLET_TRANSACTION_STATUS_UNAPPROVED},
    {"hnsWalletTransactionStatusApproved",
     IDS_HNS_WALLET_TRANSACTION_STATUS_APPROVED},
    {"hnsWalletTransactionStatusRejected",
     IDS_HNS_WALLET_TRANSACTION_STATUS_REJECTED},
    {"hnsWalletTransactionStatusSubmitted",
     IDS_HNS_WALLET_TRANSACTION_STATUS_SUBMITTED},
    {"hnsWalletTransactionStatusConfirmed",
     IDS_HNS_WALLET_TRANSACTION_STATUS_CONFIRMED},
    {"hnsWalletTransactionStatusError",
     IDS_HNS_WALLET_TRANSACTION_STATUS_ERROR},
    {"hnsWalletTransactionStatusDropped",
     IDS_HNS_WALLET_TRANSACTION_STATUS_DROPPED},
    {"hnsWalletTransactionStatusSigned",
     IDS_HNS_WALLET_TRANSACTION_STATUS_SIGNED},
    {"hnsWalletRecentTransactions", IDS_HNS_WALLET_RECENT_TRANSACTIONS},
    {"hnsWalletTransactionDetails", IDS_HNS_WALLET_TRANSACTION_DETAILS},
    {"hnsWalletTransactionDetailDate",
     IDS_HNS_WALLET_TRANSACTION_DETAIL_DATE},
    {"hnsWalletTransactionDetailSpeedUp",
     IDS_HNS_WALLET_TRANSACTION_DETAIL_SPEEDUP},
    {"hnsWalletTransactionDetailHash",
     IDS_HNS_WALLET_TRANSACTION_DETAIL_HASH},
    {"hnsWalletTransactionDetailNetwork",
     IDS_HNS_WALLET_TRANSACTION_DETAIL_NETWORK},
    {"hnsWalletTransactionDetailStatus",
     IDS_HNS_WALLET_TRANSACTION_DETAIL_STATUS},
    {"hnsWalletTransactionPlaceholder",
     IDS_HNS_WALLET_TRANSACTION_PLACEHOLDER},
    {"hnsWalletTransactionApproveUnlimited",
     IDS_HNS_WALLET_TRANSACTION_APPROVE_UNLIMITED},
    {"hnsWalletEditGasTitle1", IDS_HNS_WALLET_EDIT_GAS_TITLE1},
    {"hnsWalletEditGasTitle2", IDS_HNS_WALLET_EDIT_GAS_TITLE2},
    {"hnsWalletEditGasDescription", IDS_HNS_WALLET_EDIT_GAS_DESCRIPTION},
    {"hnsWalletEditGasLow", IDS_HNS_WALLET_EDIT_GAS_LOW},
    {"hnsWalletEditGasOptimal", IDS_HNS_WALLET_EDIT_GAS_OPTIMAL},
    {"hnsWalletEditGasHigh", IDS_HNS_WALLET_EDIT_GAS_HIGH},
    {"hnsWalletEditGasLimit", IDS_HNS_WALLET_EDIT_GAS_LIMIT},
    {"hnsWalletEditGasPerGasPrice", IDS_HNS_WALLET_EDIT_GAS_PER_GAS_PRICE},
    {"hnsWalletEditGasPerTipLimit", IDS_HNS_WALLET_EDIT_GAS_PER_TIP_LIMIT},
    {"hnsWalletEditGasPerPriceLimit",
     IDS_HNS_WALLET_EDIT_GAS_PER_PRICE_LIMIT},
    {"hnsWalletEditGasMaxFee", IDS_HNS_WALLET_EDIT_GAS_MAX_FEE},
    {"hnsWalletEditGasMaximumFee", IDS_HNS_WALLET_EDIT_GAS_MAXIMUM_FEE},
    {"hnsWalletEditGasBaseFee", IDS_HNS_WALLET_EDIT_GAS_BASE_FEE},
    {"hnsWalletEditGasGwei", IDS_HNS_WALLET_EDIT_GAS_GWEI},
    {"hnsWalletEditGasSetCustom", IDS_HNS_WALLET_EDIT_GAS_SET_CUSTOM},
    {"hnsWalletEditGasSetSuggested", IDS_HNS_WALLET_EDIT_GAS_SET_SUGGESTED},
    {"hnsWalletEditGasZeroGasPriceWarning",
     IDS_HNS_WALLET_EDIT_GAS_ZERO_GAS_PRICE_WARNING},
    {"hnsWalletAdvancedTransactionSettings",
     IDS_HNS_WALLET_ADVANCED_TRANSACTION_SETTINGS},
    {"hnsWalletAdvancedTransactionSettingsPlaceholder",
     IDS_HNS_WALLET_ADVANCED_TRANSACTION_SETTINGS_PLACEHOLDER},
    {"hnsWalletEditNonce", IDS_HNS_WALLET_EDIT_NONCE},
    {"hnsWalletEditNonceInfo", IDS_HNS_WALLET_EDIT_NONCE_INFO},
    {"hnsWalletEditPermissionsTitle",
     IDS_HNS_WALLET_EDIT_PERMISSIONS_TITLE},
    {"hnsWalletEditPermissionsDescription",
     IDS_HNS_WALLET_EDIT_PERMISSIONS_DESCRIPTION},
    {"hnsWalletEditPermissionsButton",
     IDS_HNS_WALLET_EDIT_PERMISSIONS_BUTTON},
    {"hnsWalletEditPermissionsProposedAllowance",
     IDS_HNS_WALLET_EDIT_PERMISSIONS_PROPOSED_ALLOWANCE},
    {"hnsWalletEditPermissionsCustomAllowance",
     IDS_HNS_WALLET_EDIT_PERMISSIONS_CUSTOM_ALLOWANCE},
    {"hnsWalletNotValidEthAddress", IDS_HNS_WALLET_NOT_VALID_ETH_ADDRESS},
    {"hnsWalletNotValidSolAddress", IDS_HNS_WALLET_NOT_VALID_SOL_ADDRESS},
    {"hnsWalletNotValidAddress", IDS_HNS_WALLET_NOT_VALID_ADDRESS},
    {"hnsWalletNotDomain", IDS_HNS_WALLET_NOT_DOMAIN},
    {"hnsWalletSameAddressError", IDS_HNS_WALLET_SAME_ADDRESS_ERROR},
    {"hnsWalletContractAddressError",
     IDS_HNS_WALLET_CONTRACT_ADDRESS_ERROR},
    {"hnsWalletFailedChecksumTitle", IDS_HNS_WALLET_FAILED_CHECKSUM_TITLE},
    {"hnsWalletFailedChecksumDescription",
     IDS_HNS_WALLET_FAILED_CHECKSUM_DESCRIPTION},
    {"hnsWalletHowToSolve", IDS_HNS_WALLET_HOW_TO_SOLVE},
    {"hnsWalletAddressMissingChecksumInfoWarning",
     IDS_HNS_WALLET_ADDRESS_MISSING_CHECKSUM_INFO_WARNING},
    {"hnsWalletNotValidChecksumAddressError",
     IDS_HNS_WALLET_NOT_VALID_CHECKSUM_ADDRESS_ERROR},
    {"hnsWalletMissingGasLimitError",
     IDS_HNS_WALLET_MISSING_GAS_LIMIT_ERROR},
    {"hnsWalletZeroBalanceError", IDS_HNS_WALLET_ZERO_BALANCE_ERROR},
    {"hnsWalletAddressRequiredError",
     IDS_HNS_WALLET_ADDRESS_REQUIRED_ERROR},
    {"hnsWalletInvalidRecipientAddress",
     IDS_HNS_WALLET_INVALID_RECIPIENT_ADDRESS},
    {"hnsWalletChecksumModalTitle", IDS_HNS_WALLET_CHECKSUM_MODAL_TITLE},
    {"hnsWalletChecksumModalDescription",
     IDS_HNS_WALLET_CHECKSUM_MODAL_DESCRIPTION},
    {"hnsWalletChecksumModalStepOneTitle",
     IDS_HNS_WALLET_CHECKSUM_MODAL_STEP_ONE_TITLE},
    {"hnsWalletChecksumModalStepOneDescription",
     IDS_HNS_WALLET_CHECKSUM_MODAL_STEP_ONE_DESCRIPTION},
    {"hnsWalletChecksumModalStepTwoTitle",
     IDS_HNS_WALLET_CHECKSUM_MODAL_STEP_TWO_TITLE},
    {"hnsWalletChecksumModalStepTwoDescription",
     IDS_HNS_WALLET_CHECKSUM_MODAL_STEP_TWO_DESCRIPTION},
    {"hnsWalletChecksumModalNeedHelp",
     IDS_HNS_WALLET_CHECKSUM_MODAL_NEED_HELP},
    {"hnsWalletQueueOf", IDS_HNS_WALLET_QUEUE_OF},
    {"hnsWalletQueueNext", IDS_HNS_WALLET_QUEUE_NEXT},
    {"hnsWalletQueueFirst", IDS_HNS_WALLET_QUEUE_FIRST},
    {"hnsWalletQueueRejectAll", IDS_HNS_WALLET_QUEUE_REJECT_ALL},
    {"hnsWalletSwapInsufficientBalance",
     IDS_HNS_WALLET_SWAP_INSUFFICIENT_BALANCE},
    {"hnsWalletSwapInsufficientFundsForGas",
     IDS_HNS_WALLET_SWAP_INSUFFICIENT_FUNDS_FOR_GAS},
    {"hnsWalletSwapInsufficientLiquidity",
     IDS_HNS_WALLET_SWAP_INSUFFICIENT_LIQUIDITY},
    {"hnsWalletSwapInsufficientAllowance",
     IDS_HNS_WALLET_SWAP_INSUFFICIENT_ALLOWANCE},
    {"hnsWalletSwapUnknownError", IDS_HNS_WALLET_SWAP_UNKNOWN_ERROR},
    {"hnsWalletSwapReviewSpend", IDS_HNS_WALLET_SWAP_REVIEW_SPEND},
    {"hnsWalletSwapReviewReceive", IDS_HNS_WALLET_SWAP_REVIEW_RECEIVE},
    {"hnsWalletSwapReviewHeader", IDS_HNS_WALLET_SWAP_REVIEW_HEADER},
    {"hnsWalletUnlockError", IDS_HNS_WALLET_UNLOCK_ERROR},
    {"hnsWalletDeviceUnknownScheme", IDS_HNS_WALLET_UNKNOWN_SCHEME_ERROR},
    {"hnsWalletApprovalTransactionIntent",
     IDS_HNS_WALLET_APPROVAL_TRANSACTION_INTENT},
    {"hnsWalletNoAccountsWithABalance",
     IDS_HNS_WALLET_NO_ACCOUNTS_WITH_A_BALANCE},
    {"hnsWalletNoAccountsWithABalanceDescription",
     IDS_HNS_WALLET_NO_ACCOUNTS_WITH_A_BALANCE_DESCRIPTION},
    {"hnsWalletLedgerFilecoinUnlockError",
     IDS_HNS_WALLET_LEDGER_FILECOIN_UNLOCK_ERROR},
    {"hnsWalletLedgerValidationError",
     IDS_HNS_WALLET_LEDGER_VALIDATION_ERROR},
    {"hnsWalletHardwareAccountNotFound",
     IDS_HNS_WALLET_HARDWARE_ACCOUNT_NOT_FOUND_ERROR},
    {"hnsWalletCreateBridgeError",
     IDS_HNS_WALLET_HARDWARE_CREATE_BRIDGE_ERROR},
    {"hnsWalletProcessTransactionError",
     IDS_HNS_WALLET_HARDWARE_PROCESS_TRANSACTION_ERROR},
    {"hnsWalletApproveTransactionError",
     IDS_HNS_WALLET_HARDWARE_APPROVE_TRANSACTION_ERROR},
    {"hnsWalletTransactionNotFoundSignError",
     IDS_HNS_WALLET_HARDWARE_TRANSACTION_NOT_FOUND_ERROR},
    {"hnsWalletSignOnDeviceError",
     IDS_HNS_WALLET_HARDWARE_TRANSACTION_DEVICE_ERROR},
    {"hnsWalletNoMessageToSignError",
     IDS_HNS_WALLET_HARDWARE_TRANSACTION_NO_MESSAGE_TO_SIGN_ERROR},
    {"hnsWalletProcessMessageError",
     IDS_HNS_WALLET_HARDWARE_SIGN_MESSAGE_ERROR},
    {"hnsWalletHardwareOperationUnsupportedError",
     IDS_HNS_WALLET_HARDWARE_OPERATION_UNSUPPORTED_ERROR},
    {"hnsWalletUnknownKeyringError",
     IDS_HNS_WALLET_HARDWARE_UNKNOWN_KEYRING_ERROR},
    {"hnsWalletBridgeCommandInProgress",
     IDS_HNS_WALLET_HARDWARE_COMMAND_IN_PROGRESS_ERROR},
    {"hnsWalletBridgeNotReady",
     IDS_HNS_WALLET_HARDWARE_BRIDGE_NOT_READY_ERROR},
    {"hnsWalletAddSuggestedTokenTitle",
     IDS_HNS_WALLET_ADD_SUGGESTED_TOKEN_TITLE},
    {"hnsWalletAddSuggestedTokenDescription",
     IDS_HNS_WALLET_ADD_SUGGESTED_TOKEN_DESCRIPTION},
    {"hnsWalletNFTDetailBlockchain", IDS_HNS_WALLET_NFT_DETAIL_BLOCKCHAIN},
    {"hnsWalletNFTDetailTokenStandard",
     IDS_HNS_WALLET_NFT_DETAIL_TOKEN_STANDARD},
    {"hnsWalletNFTDetailTokenID", IDS_HNS_WALLET_NFT_DETAIL_TOKEN_ID},
    {"hnsWalletNFTDetailContractAddress",
     IDS_HNS_WALLET_NFT_DETAIL_CONTRACT_ADDRESS},
    {"hnsWalletNFTDetailDescription",
     IDS_HNS_WALLET_NFT_DETAIL_DESCRIPTION},
    {"hnsWalletNFTDetailImageAddress",
     IDS_HNS_WALLET_NFT_DETAIL_IMAGE_ADDRESS},
    {"hnsWalletNFTDetailsPinningInProgress",
     IDS_HNS_WALLET_NFT_DETAILS_PINNING_IN_PROGRESS},
    {"hnsWalletNFTDetailsPinningSuccessful",
     IDS_HNS_WALLET_NFT_DETAILS_PINNING_SUCCESSFUL},
    {"hnsWalletNFTDetailsPinningFailed",
     IDS_HNS_WALLET_NFT_DETAILS_PINNING_FAILED},
    {"hnsWalletNFTDetailsOverview", IDS_HNS_WALLET_NFT_DETAILS_OVERVIEW},
    {"hnsWalletNFTDetailsOwnedBy", IDS_HNS_WALLET_NFT_DETAILS_OWNED_BY},
    {"hnsWalletNFTDetailsViewAccount",
     IDS_HNS_WALLET_NFT_DETAILS_VIEW_ACCOUNT},
    {"hnsWalletNFTDetailsPinningStatusLabel",
     IDS_HNS_WALLET_NFT_DETAILS_PINNING_STATUS_LABEL},
    {"hnsWalletNFTDetailsCid", IDS_HNS_WALLET_NFT_DETAILS_CID},
    {"hnsWalletNFTDetailsNotAvailable",
     IDS_HNS_WALLET_NFT_DETAILS_NOT_AVAILABLE},
    {"hnsWalletNFTDetailsProperties",
     IDS_HNS_WALLET_NFT_DETAILS_PROPERTIES},
    {"hnsWalletTrezorSignTypedDataError",
     IDS_HNS_WALLET_TREZOR_SIGN_TYPED_DATA_ERROR},
    {"hnsWalletSweepstakesTitle", IDS_HNS_WALLET_SWEEPSTAKES_TITLE},
    {"hnsWalletSweepstakesDescription",
     IDS_HNS_WALLET_SWEEPSTAKES_DESCRIPTION},
    {"hnsWalletSweepstakesCallToAction",
     IDS_HNS_WALLET_SWEEPSTAKES_CALL_TO_ACTION},
    {"hnsWalletNotValidFilAddress", IDS_HNS_WALLET_NOT_VALID_FIL_ADDRESS},
    {"hnsWalletBuyWithRamp", IDS_HNS_WALLET_BUY_WITH_RAMP},
    {"hnsWalletSellWithProvider", IDS_HNS_WALLET_SELL_WITH_PROVIDER},
    {"hnsWalletBuyDisclaimer", IDS_HNS_WALLET_BUY_DISCLAIMER},
    {"hnsWalletBuyWithSardine", IDS_HNS_WALLET_BUY_WITH_SARDINE},
    {"hnsWalletBuyWithTransak", IDS_HNS_WALLET_BUY_WITH_TRANSAK},
    {"hnsWalletBuyWithStripe", IDS_HNS_WALLET_BUY_WITH_STRIPE},
    {"hnsWalletBuyWithCoinbase", IDS_HNS_WALLET_BUY_WITH_COINBASE},
    {"hnsWalletBuyRampNetworkName", IDS_HNS_WALLET_BUY_RAMP_NETWORK_NAME},
    {"hnsWalletBuySardineName", IDS_HNS_WALLET_BUY_SARDINE_NAME},
    {"hnsWalletBuyTransakName", IDS_HNS_WALLET_BUY_TRANSAK_NAME},
    {"hnsWalletBuyStripeName", IDS_HNS_WALLET_BUY_STRIPE_NAME},
    {"hnsWalletBuyCoinbaseName", IDS_HNS_WALLET_BUY_COINBASE_NAME},
    {"hnsWalletBuyRampDescription", IDS_HNS_WALLET_BUY_RAMP_DESCRIPTION},
    {"hnsWalletBuySardineDescription",
     IDS_HNS_WALLET_BUY_SARDINE_DESCRIPTION},
    {"hnsWalletBuyTransakDescription",
     IDS_HNS_WALLET_BUY_TRANSAK_DESCRIPTION},
    {"hnsWalletBuyStripeDescription",
     IDS_HNS_WALLET_BUY_STRIPE_DESCRIPTION},
    {"hnsWalletBuyCoinbaseDescription",
     IDS_HNS_WALLET_BUY_COINBASE_DESCRIPTION},
    {"hnsWalletNetworkFilterAll", IDS_HNS_WALLET_NETWORK_FILTER_ALL},
    {"hnsWalletAssetFilterLowToHigh",
     IDS_HNS_WALLET_ASSET_FILTER_LOW_TO_HIGH},
    {"hnsWalletAssetFilterHighToLow",
     IDS_HNS_WALLET_ASSET_FILTER_HIGH_TO_LOW},
    {"hnsWalletAssetFilterAToZ", IDS_HNS_WALLET_ASSET_FILTER_A_TO_Z},
    {"hnsWalletAssetFilterZToA", IDS_HNS_WALLET_ASSET_FILTER_Z_TO_A},
    {"hnsWalletNone", IDS_HNS_WALLET_NONE},
    {"hnsWalletNetworks", IDS_HNS_WALLET_NETWORKS},
    {"hnsWalletPortfolioGroupByTitle",
     IDS_HNS_WALLET_PORTFOLIO_GROUP_BY_TITLE},
    {"hnsWalletPortfolioGroupByDescription",
     IDS_HNS_WALLET_PORTFOLIO_GROUP_BY_DESCRIPTION},
    {"hnsWalletPortfolioFiltersTitle",
     IDS_HNS_WALLET_PORTFOLIO_FILTERS_TITLE},
    {"hnsWalletPortfolioNftsFiltersTitle",
     IDS_HNS_WALLET_PORTFOLIO_NFTS_FILTERS_TITLE},
    {"hnsWalletSortAssets", IDS_HNS_WALLET_SORT_ASSETS},
    {"hnsWalletSortAssetsDescription",
     IDS_HNS_WALLET_SORT_ASSETS_DESCRIPTION},
    {"hnsWalletHideSmallBalances", IDS_HNS_WALLET_SMALL_BALANCES},
    {"hnsWalletHideSmallBalancesDescription",
     IDS_HNS_WALLET_SMALL_BALANCES_DESCRIPTION},
    {"hnsWalletSelectAccounts", IDS_HNS_WALLET_SELECT_ACCOUNTS},
    {"hnsWalletSelectNetworks", IDS_HNS_WALLET_SELECT_NETWORKS},
    {"hnsWalletSelectAll", IDS_HNS_WALLET_SELECT_ALL},
    {"hnsWalletDeselectAll", IDS_HNS_WALLET_DESELECT_ALL},
    {"hnsWalletPrimaryNetworks", IDS_HNS_WALLET_PRIMARY_NETWORKS},
    {"hnsWalletETHAccountDescrption",
     IDS_HNS_WALLET_ETH_ACCOUNT_DESCRIPTION},
    {"hnsWalletSOLAccountDescrption",
     IDS_HNS_WALLET_SOL_ACCOUNT_DESCRIPTION},
    {"hnsWalletFILAccountDescrption",
     IDS_HNS_WALLET_FIL_ACCOUNT_DESCRIPTION},
    {"hnsWalletBTCAccountDescrption",
     IDS_HNS_WALLET_BTC_ACCOUNT_DESCRIPTION},
    {"hnsWalletShowNetworkLogoOnNftsTitle",
     IDS_HNS_WALLET_SHOW_NETWORK_LOGO_ON_NFTS_TITLE},
    {"hnsWalletShowNetworkLogoOnNftsDescription",
     IDS_HNS_WALLET_SHOW_NETWORK_LOGO_ON_NFTS_DESCRIPTION},
    {"hnsWalletShowSpamNftsTitle", IDS_HNS_WALLET_SHOW_SPAM_NFTS_TITLE},
    {"hnsWalletShowSpamNftsDescription",
     IDS_HNS_WALLET_SHOW_SPAM_NFTS_DESCRIPTION},
    {"hnsWalletAccountFilterAllAccounts",
     IDS_HNS_WALLET_ACCOUNT_FILTER_ALL_ACCOUNTS},
    {"hnsWalletTransactionSubmittedTitle",
     IDS_HNS_WALLET_TRANSACTION_SUBMITTED_TITLE},
    {"hnsWalletTransactionSubmittedDescription",
     IDS_HNS_WALLET_TRANSACTION_SUBMITTED_DESCRIPTION},
    {"hnsWalletTransactionSignedTitle",
     IDS_HNS_WALLET_TRANSACTION_SIGNED_TITLE},
    {"hnsWalletTransactionSignedDescription",
     IDS_HNS_WALLET_TRANSACTION_SIGNED_DESCRIPTION},
    {"hnsWalletTransactionFailedHeaderTitle",
     IDS_HNS_WALLET_TRANSACTION_FAILED_HEADER_TITLE},
    {"hnsWalletTransactionFailedTitle",
     IDS_HNS_WALLET_TRANSACTION_FAILED_TITLE},
    {"hnsWalletTransactionFailedDescription",
     IDS_HNS_WALLET_TRANSACTION_FAILED_DESCRIPTION},
    {"hnsWalletTransactionFailedSwapNextCTA",
     IDS_HNS_WALLET_TRANSACTION_FAILED_SWAP_NEXT_CTA},
    {"hnsWalletTransactionFailedNextCTA",
     IDS_HNS_WALLET_TRANSACTION_FAILED_NEXT_CTA},
    {"hnsWalletTransactionFailedViewErrorCTA",
     IDS_HNS_WALLET_TRANSACTION_FAILED_VIEW_ERROR_CTA},
    {"hnsWalletTransactionFailedReceiptCTA",
     IDS_HNS_WALLET_TRANSACTION_FAILED_RECEIPT_CTA},
    {"hnsWalletTransactionFailedModalTitle",
     IDS_HNS_WALLET_TRANSACTION_FAILED_MODAL_TITLE},
    {"hnsWalletTransactionFailedModalSubtitle",
     IDS_HNS_WALLET_TRANSACTION_FAILED_MODAL_SUBTITLE},
    {"hnsWalletTransactionCompleteSwapHeaderTitle",
     IDS_HNS_WALLET_TRANSACTION_COMPLETE_SWAP_HEADER_TITLE},
    {"hnsWalletTransactionCompleteTitle",
     IDS_HNS_WALLET_TRANSACTION_COMPLETE_TITLE},
    {"hnsWalletTransactionCompleteDescription",
     IDS_HNS_WALLET_TRANSACTION_COMPLETE_DESCRIPTION},
    {"hnsWalletTransactionCompleteReceiptCTA",
     IDS_HNS_WALLET_TRANSACTION_COMPLETE_RECEIPT_CTA},
    {"hnsWalletTransactionConfirmingTitle",
     IDS_HNS_WALLET_TRANSACTION_CONFIRMING_TITLE},
    {"hnsWalletTransactionConfirmingDescription",
     IDS_HNS_WALLET_TRANSACTION_CONFIRMING_DESCRIPTION},
    {"hnsWalletTransactionConfirmingText",
     IDS_HNS_WALLET_TRANSACTION_CONFIRMING_TEXT},
    {"hnsWalletTransactionIntentDappInteraction",
     IDS_HNS_WALLET_TRANSACTION_INTENT_DAPP_INTERACTION},
    {"hnsWalletTransactionIntentSend",
     IDS_HNS_WALLET_TRANSACTION_INTENT_SEND},
    {"hnsWalletTransactionIntentSwap",
     IDS_HNS_WALLET_TRANSACTION_INTENT_SWAP},
    {"hnsWalletEditGasLimitError", IDS_HNS_WALLET_EDIT_GAS_LIMIT_ERROR},
    {"hnsWalletApproveTransaction", IDS_HNS_WALLET_APPROVE_TRANSACTION},
    {"hnsWalletSolanaSystemProgram", IDS_HNS_WALLET_SOLANA_SYSTEM_PROGRAM},
    {"hnsWalletSolanaConfigProgram", IDS_HNS_WALLET_SOLANA_CONFIG_PROGRAM},
    {"hnsWalletSolanaStakeProgram", IDS_HNS_WALLET_SOLANA_STAKE_PROGRAM},
    {"hnsWalletSolanaVoteProgram", IDS_HNS_WALLET_SOLANA_VOTE_PROGRAM},
    {"hnsWalletSolanaBPFLoader", IDS_HNS_WALLET_SOLANA_BP_FLOADER},
    {"hnsWalletSolanaAccounts", IDS_HNS_WALLET_SOLANA_ACCOUNTS},
    {"hnsWalletSolanaData", IDS_HNS_WALLET_SOLANA_DATA},
    {"hnsWalletSolanaProgramID", IDS_HNS_WALLET_SOLANA_PROGRAM_ID},
    {"hnsWalletSolanaMaxRetries", IDS_HNS_WALLET_SOLANA_MAX_RETRIES},
    {"hnsWalletSolanaPreflightCommitment",
     IDS_HNS_WALLET_SOLANA_PREFLIGHT_COMMITMENT},
    {"hnsWalletSolanaSkipPreflight", IDS_HNS_WALLET_SOLANA_SKIP_PREFLIGHT},
    {"hnsWalletSolanaAddressLookupTableAccount",
     IDS_HNS_WALLET_SOLANA_ADDRESS_LOOKUP_TABLE_ACCOUNT},
    {"hnsWalletSolanaAddressLookupTableIndex",
     IDS_HNS_WALLET_SOLANA_ADDRESS_LOOKUP_TABLE_INDEX},
    {"hnsWalletSolanaEd25519Program",
     IDS_HNS_WALLET_SOLANA_ED25519_PROGRAM},
    {"hnsWalletSolanaSecp256k1Program",
     IDS_HNS_WALLET_SOLANA_SECP256K1_PROGRAM},
    {"hnsWalletNetworkFilterSecondary",
     IDS_HNS_WALLET_NETWORK_FILTER_SECONDARY},
    {"hnsWalletNetworkFilterTestNetworks",
     IDS_HNS_WALLET_NETWORK_FILTER_TEST_NETWORKS},
    {"hnsWalletSelectCurrency", IDS_HNS_WALLET_SELECT_CURRENCY},
    {"hnsWalletSearchCurrency", IDS_HNS_WALLET_SEARCH_CURRENCY},
    {"hnsWalletHelpCenter", IDS_HNS_WALLET_HELP_CENTER},
    {"hnsWalletHelpCenterText", IDS_HNS_WALLET_HELP_CENTER_TEXT},
    {"hnsWalletBuyTapBuyNotSupportedMessage",
     IDS_HNS_WALLET_BUY_TAB_BUY_NOT_SUPPORTED_MESSAGE},
    {"hnsWalletAuroraModalTitle", IDS_HNS_WALLET_AURORA_MODAL_TITLE},
    {"hnsWalletAuroraModalDescription",
     IDS_HNS_WALLET_AURORA_MODAL_DESCRIPTION},
    {"hnsWalletAuroraModalLearnMore",
     IDS_HNS_WALLET_AURORA_MODAL_LEARN_MORE},
    {"hnsWalletAuroraModalLearnMoreAboutRisk",
     IDS_HNS_WALLET_AURORA_MODAL_LEARN_MORE_ABOUT_RISK},
    {"hnsWalletAuroraModalDontShowAgain",
     IDS_HNS_WALLET_AURORA_MODAL_DONT_SHOW_AGAIN},
    {"hnsWalletAuroraModalOPenButtonText",
     IDS_HNS_WALLET_AURORA_MODAL_OPEN_BUTTON_TEXT},
    {"hnsWalletBridgeToAuroraButton",
     IDS_HNS_WALLET_BRIDGE_TO_AURORA_BUTTON},
    {"hnsWalletPasswordStrengthTooltipHeading",
     IDS_HNS_WALLET_PASSWORD_STRENGTH_TOOLTIP_HEADING},
    {"hnsWalletPasswordStrengthTooltipIsLongEnough",
     IDS_HNS_WALLET_PASSWORD_STRENGTH_TOOLTIP_IS_LONG_ENOUGH},
    {"hnsWalletPasswordMatch", IDS_HNS_WALLET_PASSWORD_MATCH},
    {"hnsWalletPasswordIsStrong", IDS_HNS_WALLET_PASSWORD_IS_STRONG},
    {"hnsWalletPasswordIsMediumStrength",
     IDS_HNS_WALLET_PASSWORD_IS_MEDIUM_STRENGTH},
    {"hnsWalletPasswordIsWeak", IDS_HNS_WALLET_PASSWORD_IS_WEAK},
    {"hnsWalletOnboardingRecoveryPhraseBackupIntroTitle",
     IDS_HNS_WALLET_ONBOARDING_RECOVERY_PHRASE_BACKUP_INTRO_TITLE},
    {"hnsWalletOnboardingRecoveryPhraseBackupIntroDescription",
     IDS_HNS_WALLET_ONBOARDING_RECOVERY_PHRASE_BACKUP_INTRO_DESCRIPTION},
    {"hnsWalletRecoveryPhraseBackupWarning",
     IDS_HNS_WALLET_RECOVERY_PHRASE_BACKUP_WARNING},
    {"hnsWalletRecoveryPhraseBackupWarningImportant",
     IDS_HNS_WALLET_RECOVERY_PHRASE_BACKUP_WARNING_IMPORTANT},
    {"hnsWalletRecoveryPhraseBackupTitle",
     IDS_HNS_WALLET_RECOVERY_PHRASE_BACKUP_TITLE},
    {"hnsWalletCopiedToClipboard", IDS_HNS_WALLET_COPIED_TO_CLIPBOARD},
    {"hnsWalletClickToSeeRecoveryPhrase",
     IDS_HNS_WALLET_CLICK_TO_SEE_RECOVERY_PHRASE},
    {"hnsWalletOrdinalFirst", IDS_HNS_WALLET_ORDINAL_FIRST},
    {"hnsWalletOrdinalThird", IDS_HNS_WALLET_ORDINAL_THIRD},
    {"hnsWalletOnboardingSuccessTitle",
     IDS_HNS_WALLET_ONBOARDING_SUCCESS_TITLE},
    {"hnsWalletOnboardingSuccessDescription",
     IDS_HNS_WALLET_ONBOARDING_SUCCESS_DESCRIPTION},
    {"hnsWalletArticleLinkWhatsARecoveryPhrase",
     IDS_HNS_WALLET_ARTICLE_LINK_WHATS_A_RECOVERY_PHRASE},
    {"hnsWalletImportOrRestoreWalletTitle",
     IDS_HNS_WALLET_IMPORT_OR_RESTORE_WALLET_TITLE},
    {"hnsWalletImportOrRestoreDescription",
     IDS_HNS_WALLET_IMPORT_OR_RESTORE_DESCRIPTION},
    {"hnsWalletRestoreMyHnsWallet",
     IDS_HNS_WALLET_RESTORE_MY_HNS_WALLET},
    {"hnsWalletRestoreMyHnsWalletInstructions",
     IDS_HNS_WALLET_RESTORE_MY_HNS_WALLET_INSTRUCTIONS},
    {"hnsWalletRestoreMyHnsWalletDescription",
     IDS_HNS_WALLET_RESTORE_MY_HNS_WALLET_DESCRIPTION},
    {"hnsWalletImportFromMetaMask", IDS_HNS_WALLET_IMPORT_FROM_META_MASK},
    {"hnsWalletImportFromMetaMaskDescription",
     IDS_HNS_WALLET_IMPORT_FROM_META_MASK_DESCRIPTION},
    {"hnsWalletImportFromMetaMaskSeedInstructions",
     IDS_HNS_WALLET_IMPORT_FROM_META_MASK_SEED_INSTRUCTIONS},
    {"hnsWalletCreateWalletInsteadLink",
     IDS_HNS_WALLET_CREATE_WALLET_INSTEAD_LINK},
    {"hnsWalletImportPasswordError", IDS_HNS_WALLET_IMPORT_PASSWORD_ERROR},
    {"hnsWalletMetaMaskExtensionDetected",
     IDS_HNS_WALLET_METAMASK_EXTENSION_DETECTED},
    {"hnsWalletMetaMaskExtensionImportDescription",
     IDS_HNS_WALLET_METAMASK_EXTENSION_IMPORT_DESCRIPTION},
    {"hnsWalletMetaMaskPasswordInputPlaceholder",
     IDS_HNS_WALLET_METAMASK_PASSWORD_INPUT_PLACEHOLDER},
    {"hnsWalletInputLabelPassword", IDS_HNS_WALLET_INPUT_LABEL_PASSWORD},
    {"hnsWalletLearnAboutMyWallet", IDS_HNS_WALLET_LEARN_ABOUT_MY_WALLET},
    {"hnsWalletDisclosuresTitle", IDS_HNS_WALLET_DISCLOSURES_TITLE},
    {"hnsWalletDisclosuresDescription",
     IDS_HNS_WALLET_DISCLOSURES_DESCRIPTION},
    {"hnsWalletSelfCustodyDisclosureCheckboxText",
     IDS_HNS_WALLET_SELF_CUSTODY_DISCLOSURE_CHECKBOX_TEXT},
    {"hnsWalletTermsOfServiceCheckboxText",
     IDS_HNS_WALLET_TERMS_OF_SERVICE_CHECKBOX_TEXT},
    {"hnsWalletBuyCryptoButton", IDS_HNS_WALLET_BUY_CRYPTO_BUTTON},
    {"hnsWalletDepositCryptoButton", IDS_HNS_WALLET_DEPOSIT_CRYPTO_BUTTON},
    {"hnsWalletCheckingInstalledExtensions",
     IDS_HNS_WALLET_CHECKING_INSTALLED_EXTENSIONS},
    {"hnsWalletImportFromLegacy", IDS_HNS_WALLET_IMPORT_FROM_LEGACY},
    {"hnsWalletBuySelectAsset", IDS_HNS_WALLET_BUY_SELECT_ASSET},
    {"hnsWalletFundWalletTitle", IDS_HNS_WALLET_FUND_WALLET_TITLE},
    {"hnsWalletDepositFundsTitle", IDS_HNS_WALLET_DEPOSIT_FUNDS_TITLE},
    {"hnsWalletDepositX", IDS_HNS_WALLET_DEPOSIT_X},
    {"hnsWalletDepositSolSplTokens", IDS_HNS_WALLET_DEPOSIT_SOL_SPL_TOKENS},
    {"hnsWalletDepositErc", IDS_HNS_WALLET_DEPOSIT_ERC},
    {"hnsWalletDepositOnlySendOnXNetwork",
     IDS_HNS_WALLET_DEPOSIT_ONLY_SEND_ON_X_NETWORK},
    {"hnsWalletFundWalletDescription",
     IDS_HNS_WALLET_FUND_WALLET_DESCRIPTION},
    {"hnsWalletLearnMoreAboutHnsWallet",
     IDS_HNS_WALLET_LEARN_MORE_ABOUT_HNS_WALLET},
    {"hnsWalletMarketDataAllAssetsFilter",
     IDS_HNS_WALLET_MARKET_DATA_ALL_ASSETS_FILTER},
    {"hnsWalletMarketDataTradableFilter",
     IDS_HNS_WALLET_MARKET_DATA_TRADABLE_FILTER},
    {"hnsWalletMarketDataAssetsColumn",
     IDS_HNS_WALLET_MARKET_DATA_ASSETS_COLUMN},
    {"hnsWalletMarketDataPriceColumn",
     IDS_HNS_WALLET_MARKET_DATA_PRICE_COLUMN},
    {"hnsWalletMarketData24HrColumn",
     IDS_HNS_WALLET_MARKET_DATA_24Hr_COLUMN},
    {"hnsWalletMarketDataMarketCapColumn",
     IDS_HNS_WALLET_MARKET_DATA_MARKETCAP_COLUMN},
    {"hnsWalletMarketDataVolumeColumn",
     IDS_HNS_WALLET_MARKET_DATA_VOLUME_COLUMN},
    {"hnsWalletMarketDataNoAssetsFound",
     IDS_HNS_WALLET_MARKET_DATA_NO_ASSETS_FOUND},
    {"hnsWalletInformation", IDS_HNS_WALLET_INFORMATION},
    {"hnsWalletRankStat", IDS_HNS_WALLET_RANK_STAT},
    {"hnsWalletVolumeStat", IDS_HNS_WALLET_VOLUME_STAT},
    {"hnsWalletMarketCapStat", IDS_HNS_WALLET_MARKET_CAP_STAT},
    {"hnsWalletBuyTapBuyNotSupportedMessage",
     IDS_HNS_WALLET_BUY_TAB_BUY_NOT_SUPPORTED_MESSAGE},
    {"hnsWalletHelpCenterText", IDS_HNS_WALLET_HELP_CENTER_TEXT},
    {"hnsWalletMarketDataAllAssetsFilter",
     IDS_HNS_WALLET_MARKET_DATA_ALL_ASSETS_FILTER},
    {"hnsWalletMarketDataTradableFilter",
     IDS_HNS_WALLET_MARKET_DATA_TRADABLE_FILTER},
    {"hnsWalletMarketDataAssetsColumn",
     IDS_HNS_WALLET_MARKET_DATA_ASSETS_COLUMN},
    {"hnsWalletMarketDataPriceColumn",
     IDS_HNS_WALLET_MARKET_DATA_PRICE_COLUMN},
    {"hnsWalletMarketData24HrColumn",
     IDS_HNS_WALLET_MARKET_DATA_24Hr_COLUMN},
    {"hnsWalletMarketDataMarketCapColumn",
     IDS_HNS_WALLET_MARKET_DATA_MARKETCAP_COLUMN},
    {"hnsWalletMarketDataVolumeColumn",
     IDS_HNS_WALLET_MARKET_DATA_VOLUME_COLUMN},
    {"hnsWalletMarketDataBuyDepositColumn",
     IDS_HNS_WALLET_MARKET_DATA_BUY_DEPOSIT_COLUMN},
    {"hnsWalletMarketDataNoAssetsFound",
     IDS_HNS_WALLET_MARKET_DATA_NO_ASSETS_FOUND},
    {"hnsWalletInformation", IDS_HNS_WALLET_INFORMATION},
    {"hnsWalletRankStat", IDS_HNS_WALLET_RANK_STAT},
    {"hnsWalletVolumeStat", IDS_HNS_WALLET_VOLUME_STAT},
    {"hnsWalletMarketCapStat", IDS_HNS_WALLET_MARKET_CAP_STAT},
    {"hnsWalletBuyTapBuyNotSupportedMessage",
     IDS_HNS_WALLET_BUY_TAB_BUY_NOT_SUPPORTED_MESSAGE},
    {"hnsWalletSearchingForDomain", IDS_HNS_WALLET_SEARCHING_FOR_DOMAIN},
    {"hnsWalletEnsOffChainLookupTitle",
     IDS_HNS_WALLET_ENS_OFF_CHAIN_LOOKUP_TITLE},
    {"hnsWalletEnsOffChainLookupDescription",
     IDS_HNS_WALLET_ENS_OFF_CHAIN_LOOKUP_DESCRIPTION},
    {"hnsWalletEnsOffChainButton", IDS_HNS_WALLET_ENS_OFF_CHAIN_BUTTON},
    {"hnsWalletPortfolioTokenDetailsMenuLabel",
     IDS_HNS_WALLET_PORTFOLIO_TOKEN_DETAILS_MENU_LABEL},
    {"hnsWalletPortfolioViewOnExplorerMenuLabel",
     IDS_HNS_WALLET_PORTFOLIO_VIEW_ON_EXPLORER_MENU_LABEL},
    {"hnsWalletPortfolioHideTokenMenuLabel",
     IDS_HNS_WALLET_PORTFOLIO_VIEW_HIDE_TOKEN_LABEL},
    {"hnsWalletHideTokenModalTitle", IDS_HNS_WALLET_HIDE_TOKEN_MODAL_TITLE},
    {"hnsWalletTokenContractAddress",
     IDS_HNS_WALLET_TOKEN_CONTRACT_ADDRESS},
    {"hnsWalletTokenDecimal", IDS_HNS_WALLET_TOKEN_DECIMAL},
    {"hnsWalletMakeTokenVisibleInstructions",
     IDS_HNS_WALLET_MAKE_TOKEN_VISIBLE_INSTRUCTIONS},
    {"hnsWalletConfirmHidingToken", IDS_HNS_WALLET_CONFIRM_HIDING_TOKEN},
    {"hnsWalletCancelHidingToken", IDS_HNS_WALLET_CANCEL_HIDING_TOKEN},
    {"hnsWalletMyAssets", IDS_HNS_WALLET_MY_ASSETS},
    {"hnsWalletAvailableAssets", IDS_HNS_WALLET_AVAILABLE_ASSETS},
    {"hnsWalletDidntFindAssetEndOfList",
     IDS_HNS_WALLET_DIDNT_FIND_ASSET_END_OF_LIST},
    {"hnsWalletDidntFindAssetInList",
     IDS_HNS_WALLET_DIDNT_FIND_ASSET_IN_LIST},
    {"hnsWalletAssetNotFound", IDS_HNS_WALLET_ASSET_NOT_FOUND},
    {"hnsWalletRequestFeatureButtonText",
     IDS_HNS_WALLET_REQUEST_FEATURE_BUTTON_TEXT},
    {"hnsWalletEnsOffchainProceedWithYes",
     IDS_HNS_WALLET_ENS_OFFCHAIN_PROCEED_WITH_YES},
    {"hnsWalletEnsOffchainProceedWithNo",
     IDS_HNS_WALLET_ENS_OFFCHAIN_PROCEED_WITH_NO},
    {"hnsWalletEnsOffchainDontShowAgain",
     IDS_HNS_WALLET_ENS_OFFCHAIN_DONT_SHOW_AGAIN},
    {"hnsWalletEnsOffchainWarning", IDS_HNS_WALLET_ENS_OFFCHAIN_WARNING},
    {"hnsWalletAddAssetTokenTabTitle",
     IDS_HNS_WALLET_ADD_ASSET_TOKEN_TAB_TITLE},
    {"hnsWalletAddAssetNftTabTitle",
     IDS_HNS_WALLET_ADD_ASSET_NFT_TAB_TITLE},
    {"hnsWalletNftFetchingError", IDS_HNS_WALLET_NFT_FETCHING_ERROR},
    {"hnsWalletFEVMAddressTranslationTitle",
     IDS_HNS_WALLET_FEVM_ADDRESS_TRANSLATION_TITLE},
    {"hnsWalletFEVMAddressTranslationDescription",
     IDS_HNS_WALLET_FEVM_ADDRESS_TRANSLATION_DESCRIPTION},

    // Hns Swap
    {"hnsSwap", IDS_HNS_SWAP},
    {"hnsSwapReviewOrder", IDS_HNS_SWAP_REVIEW_ORDER},
    {"hnsSwapApproveToken", IDS_HNS_SWAP_APPROVE_TOKEN},
    {"hnsSwapInsufficientBalance", IDS_HNS_SWAP_INSUFFICIENT_BALANCE},
    {"hnsSwapInsufficientLiquidity", IDS_HNS_SWAP_INSUFFICIENT_LIQUIDITY},
    {"hnsSwapSelectToken", IDS_HNS_SWAP_SELECT_TOKEN},
    {"hnsSwapHalf", IDS_HNS_SWAP_HALF},
    {"hnsSwapMax", IDS_HNS_SWAP_MAX},
    {"hnsSwapEnterAnAmount", IDS_HNS_SWAP_ENTER_AN_AMOUNT},
    {"hnsSwapFindingPrice", IDS_HNS_SWAP_FINDING_PRICE},
    {"hnsSwapBalance", IDS_HNS_SWAP_BALANCE},
    {"hnsSwapSelectAToken", IDS_HNS_SWAP_SELECT_A_TOKEN},
    {"hnsSwapShowTokensWithZeroBalances",
     IDS_HNS_SWAP_SHOW_TOKENS_WITH_ZERO_BALANCES},
    {"hnsSwapHideTokensWithZeroBalances",
     IDS_HNS_SWAP_HIDE_TOKENS_WITH_ZERO_BALANCES},
    {"hnsSwapSearchToken", IDS_HNS_SWAP_SEARCH_TOKEN},
    {"hnsSwapOption", IDS_HNS_SWAP_OPTION},
    {"hnsSwapRate", IDS_HNS_SWAP_RATE},
    {"hnsSwapPriceImpact", IDS_HNS_SWAP_PRICE_IMPACT},
    {"hnsSwapMinimumReceivedAfterSlippage",
     IDS_HNS_SWAP_MINIMUM_RECEIVED_AFTER_SLIPPAGE},
    {"hnsSwapNetworkFee", IDS_HNS_SWAP_NETWORK_FEE},
    {"hnsSwapHnsFee", IDS_HNS_SWAP_HNS_FEE},
    {"hnsSwapProtocolFee", IDS_HNS_SWAP_PROTOCOL_FEE},
    {"hnsSwapFree", IDS_HNS_SWAP_FREE},
    {"hnsSwapLiquidityProvider", IDS_HNS_SWAP_LIQUIDITY_PROVIDER},
    {"hnsSwapSwapAndSend", IDS_HNS_SWAP_SWAP_AND_SEND},
    {"hnsSwapNoExtraFees", IDS_HNS_SWAP_NO_EXTRA_FEES},
    {"hnsSwapConfirmAddress", IDS_HNS_SWAP_CONFIRM_ADDRESS},
    {"hnsSwapAddressInputePlaceholder",
     IDS_HNS_SWAP_ADDRESS_INPUT_PLACEHOLDER},
    {"hnsSwapSelectAccount", IDS_HNS_SWAP_SELECT_ACCOUNT},
    {"hnsSwapToAccount", IDS_HNS_SWAP_TO_ACCOUNT},
    {"hnsSwapToAddress", IDS_HNS_SWAP_TO_ADDRESS},
    {"hnsSwapSlow", IDS_HNS_SWAP_SLOW},
    {"hnsSwapAverage", IDS_HNS_SWAP_AVERAGE},
    {"hnsSwapFast", IDS_HNS_SWAP_FAST},
    {"hnsSwapGwei", IDS_HNS_SWAP_GWEI},
    {"hnsSwapSettings", IDS_HNS_SWAP_SETTINGS},
    {"hnsSwapSlippageTolerance", IDS_HNS_SWAP_SLIPPAGE_TOLERANCE},
    {"hnsSwapExchanges", IDS_HNS_SWAP_EXCHANGES},
    {"hnsSwapDirectRouteTitle", IDS_HNS_SWAP_DIRECT_ROUTE_TITLE},
    {"hnsSwapDirectRouteDescription",
     IDS_HNS_SWAP_DIRECT_ROUTE_DESCRIPTION},
    {"hnsSwapNetworkFeeDescription", IDS_HNS_SWAP_NETWORK_FEE_DESCRIPTION},
    {"hnsSwapCoinGeckoCheaper", IDS_HNS_SWAP_COINGECKO_CHEAPER},
    {"hnsSwapCoinGeckoWithin", IDS_HNS_SWAP_COINGECKO_WITHIN},
    {"hnsSwapCoinGeckoExpensive", IDS_HNS_SWAP_COINGECKO_EXPENSIVE},
    {"hnsSwapAPI", IDS_HNS_SWAP_API},
    {"hnsSwapName", IDS_HNS_SWAP_NAME},
    {"hnsSwapConnectWallet", IDS_HNS_SWAP_CONNECT_WALLET},
    {"hnsSwapDisconnectWallet", IDS_HNS_SWAP_DISCONNECT_WALLET},
    {"hnsSwapSwitchNetwork", IDS_HNS_SWAP_SWITCH_NETWORK},
    {"hnsSwapAdvanced", IDS_HNS_SWAP_ADVANCED},
    {"hnsSwapAccounts", IDS_HNS_SWAP_ACCOUNTS},
    {"hnsSwapWallet", IDS_HNS_SWAP_WALLET},
    {"hnsSwapBest", IDS_HNS_SWAP_BEST},
    {"hnsSwapHelpCenter", IDS_HNS_SWAP_HELP_CENTER},
    {"hnsSwapPrivacyPolicy", IDS_HNS_SWAP_PRIVACY_POLICY},
    {"hnsSwapPrivacyDescription", IDS_HNS_SWAP_PRIVACY_DESCRIPTION},
    {"hnsSwapV2Disclaimer", IDS_HNS_SWAP_V2_DISCLAIMER},
    {"hnsSwapV2Privacy", IDS_HNS_SWAP_V2_PRIVACY},
    {"hnsSwapChangeNetwork", IDS_HNS_SWAP_CHANGE_NETWORK},

    // NFT Pinning
    {"hnsWalletNftPinningWhyNotAvailable",
     IDS_HNS_WALLET_NFT_PINNING_WHY_NOT_AVAILABLE},
    {"hnsWalletNftPinningTooltip", IDS_HNS_WALLET_NFT_PINNING_TOOLTIP},
    {"hnsWalletNftPinningBenefitsHeading",
     IDS_HNS_WALLET_NFT_PINNING_BENEFITS_HEADING},
    {"hnsWalletNftPinningPinNftsButton",
     IDS_HNS_WALLET_NFT_PINNING_PIN_NFT_BUTTON},
    {"hnsWalletNftPinningBackButton",
     IDS_HNS_WALLET_NFT_PINNING_BACK_BUTTON},
    {"hnsWalletNftPinningCloseButton",
     IDS_HNS_WALLET_NFT_PINNING_CLOSE_BUTTON},
    {"hnsWalletNftPinningHeading", IDS_HNS_WALLET_NFT_PINNING_HEADING},
    {"hnsWalletNftPinningRunNodeHeading",
     IDS_HNS_WALLET_NFT_PINNING_RUN_NODE_HEADING},
    {"hnsWalletNftPinningRunNodeDescription",
     IDS_HNS_WALLET_NFT_PINNING_RUN_NODE_DESCRIPTION},
    {"hnsWalletNftPinningCheckNftsButton",
     IDS_HNS_WALLET_NFT_PINNING_CHECK_NFTS_BUTTON},
    {"hnsWalletNftPinningBannerStart",
     IDS_HNS_WALLET_NFT_PINNING_BANNER_START},
    {"hnsWalletNftPinningBannerUploading",
     IDS_HNS_WALLET_NFT_PINNING_BANNER_UPLOADING},
    {"hnsWalletNftPinningBannerSuccess",
     IDS_HNS_WALLET_NFT_PINNING_BANNER_SUCCESS},
    {"hnsWalletNftPinningBannerLearnMore",
     IDS_HNS_WALLET_NFT_PINNING_BANNER_LEARN_MORE},
    {"hnsWalletNftPinningInspectHeading",
     IDS_HNS_WALLET_NFT_PINNING_INSPECT_HEADING},
    {"hnsWalletNftPinningInspectHeadingPlural",
     IDS_HNS_WALLET_NFT_PINNING_INSPECT_HEADING_PLURAL},
    {"hnsWalletNftPinningUnableToPin",
     IDS_HNS_WALLET_NFT_PINNING_UNABLE_TO_PIN},
    {"hnsWalletNftPinningNodeRunningStatus",
     IDS_HNS_WALLET_NFT_PINNING_NODE_RUNNING_STATUS},
    {"hnsWalletNftPinningNodeNotRunningStatus",
     IDS_HNS_WALLET_NFT_PINNING_NODE_NOT_RUNNING_STATUS},
    {"hnsWalletNftPinningStatusPinned",
     IDS_HNS_WALLET_NFT_PINNING_STATUS_PINNED},
    {"hnsWalletNftPinningStatusPinning",
     IDS_HNS_WALLET_NFT_PINNING_STATUS_PINNING},
    {"hnsWalletNftPinningStatusPinningFailed",
     IDS_HNS_WALLET_NFT_PINNING_STATUS_PINNING_FAILED},
    {"hnsWalletNftPinningErrorTooltipHeading",
     IDS_HNS_WALLET_NFT_PINNING_STATUS_PINNING_TOOLTIP_HEADING},
    {"hnsWalletNftPinningErrorTooltipReasonOne",
     IDS_HNS_WALLET_NFT_PINNING_STATUS_PINNING_TOOLTIP_REASON_ONE},
    {"hnsWalletNftPinningErrorTooltipReasonTwo",
     IDS_HNS_WALLET_NFT_PINNING_STATUS_PINNING_TOOLTIP_REASON_TWO},
    {"hnsWalletNftPinningErrorTooltipReasonThree",
     IDS_HNS_WALLET_NFT_PINNING_STATUS_PINNING_TOOLTIP_REASON_THREE},
    {"hnsNftsTabImportNft", IDS_HNS_WALLET_NFTS_TAB_IMPORT_NFT},
    {"hnsNftsTabEmptyStateHeading",
     IDS_HNS_WALLET_NFTS_TAB_EMPTY_STATE_HEADING},
    {"hnsNftsTabEmptyStateSubHeading",
     IDS_HNS_WALLET_NFTS_TAB_EMPTY_STATE_SUBHEADING},
    {"hnsNftsTabEmptyStateDisclaimer",
     IDS_HNS_WALLET_NFTS_TAB_EMPTY_STATE_DISCLAIMER},
    {"hnsNftsTabHide", IDS_HNS_WALLET_NFTS_TAB_HIDE},
    {"hnsNftsTabUnhide", IDS_HNS_WALLET_NFTS_TAB_UNHIDE},
    {"hnsNftsTabEdit", IDS_HNS_WALLET_NFTS_TAB_EDIT},
    {"hnsWalletNftUnspam", IDS_HNS_WALLET_NFT_UNSPAM},
    {"hnsWalletNftJunk", IDS_HNS_WALLET_NFT_JUNK},
    {"hnsWalletRemoveNftModalHeader",
     IDS_HNS_WALLET_REMOVE_NFT_MODAL_HEADER},
    {"hnsWalletRemoveNftModalDescription",
     IDS_HNS_WALLET_REMOVE_NFT_MODAL_DESCRIPTION},
    {"hnsWalletRemoveNftModalCancel",
     IDS_HNS_WALLET_REMOVE_NFT_MODAL_CANCEL},
    {"hnsWalletRemoveNftModalConfirm",
     IDS_HNS_WALLET_REMOVE_NFT_MODAL_CONFIRM},
    {"hnsWalletNftMoveToSpam", IDS_HNS_WALLET_NFT_MOVE_TO_SPAM},
    {"hnsNftsTab", IDS_HNS_WALLET_NFTS_TAB},
    {"hnsNftsTabHidden", IDS_HNS_WALLET_NFTS_TAB_HIDDEN},
    {"hnsNftsTabCollected", IDS_HNS_WALLET_NFTS_TAB_COLLECTED},
    {"hnsNftsTabRemove", IDS_HNS_WALLET_NFTS_TAB_REMOVE},
    {"hnsWalletImportNftModalTitle", IDS_HNS_WALLET_IMPORT_NFT_MODAL_TITLE},
    {"hnsWalletEditNftModalTitle", IDS_HNS_WALLET_EDIT_NFT_MODAL_TITLE},
    {"hnsWalletEnableNftAutoDiscoveryModalHeader",
     IDS_HNS_WALLET_ENABLE_NFT_AUTODISCOVERY_MODAL_HEADER},
    {"hnsWalletEnableNftAutoDiscoveryModalDescription",
     IDS_HNS_WALLET_ENABLE_NFT_AUTODISCOVERY_MODAL_DESCRIPTION},
    {"hnsWalletEnableNftAutoDiscoveryModalConfirm",
     IDS_HNS_WALLET_ENABLE_NFT_AUTODISCOVERY_MODAL_CONFIRM},
    {"hnsWalletEnableNftAutoDiscoveryModalCancel",
     IDS_HNS_WALLET_ENABLE_NFT_AUTODISCOVERY_MODAL_CANCEL},
    {"hnsWalletAutoDiscoveryEmptyStateHeading",
     IDS_HNS_WALLET_AUTO_DISCOVERY_EMPTY_STATE_HEADING},
    {"hnsWalletAutoDiscoveryEmptyStateSubHeading",
     IDS_HNS_WALLET_AUTO_DISCOVERY_EMPTY_STATE_SUB_HEADING},
    {"hnsWalletAutoDiscoveryEmptyStateFooter",
     IDS_HNS_WALLET_AUTO_DISCOVERY_EMPTY_STATE_FOOTER},
    {"hnsWalletAutoDiscoveryEmptyStateActions",
     IDS_HNS_WALLET_AUTO_DISCOVERY_EMPTY_STATE_ACTIONS},
    {"hnsWalletAutoDiscoveryEmptyStateRefresh",
     IDS_HNS_WALLET_AUTO_DISCOVERY_EMPTY_STATE_REFRESH}};

// 0x swap constants
constexpr char kGoerliSwapBaseAPIURL[] = "https://goerli.api.0x.org/";
constexpr char kPolygonSwapBaseAPIURL[] = "https://polygon.api.0x.org/";
constexpr char kBinanceSmartChainSwapBaseAPIURL[] = "https://bsc.api.0x.org/";
constexpr char kAvalancheSwapBaseAPIURL[] = "https://avalanche.api.0x.org/";
constexpr char kFantomSwapBaseAPIURL[] = "https://fantom.api.0x.org/";
constexpr char kCeloSwapBaseAPIURL[] = "https://celo.api.0x.org/";
constexpr char kOptimismSwapBaseAPIURL[] = "https://optimism.api.0x.org/";
constexpr char kArbitrumSwapBaseAPIURL[] = "https://arbitrum.api.0x.org/";
constexpr char kBaseSwapBaseAPIURL[] = "https://base.api.0x.org/";
constexpr char kSwapBaseAPIURL[] = "https://api.0x.org/";
constexpr double k0xBuyTokenFeePercentage = 0.875;
constexpr double k0xProtocolFeePercentage = 0.15;
constexpr char kEVMFeeRecipient[] =
    "0xbd9420A98a7Bd6B89765e5715e169481602D9c3d";
constexpr char kAffiliateAddress[] =
    "0xbd9420A98a7Bd6B89765e5715e169481602D9c3d";
constexpr char k0xAPIKeyHeader[] = "0x-api-key";

// Jupiter swap constants
constexpr char kSolanaSwapBaseAPIURL[] = "https://quote-api.jup.ag/";
constexpr double kSolanaBuyTokenFeePercentage = 0.85;
constexpr char kSolanaFeeRecipient[] =
    "3NUW8hWoCnLgJwWCVnwdFo2Dsz8bKwLac9A3VgS2jLUQ";

// Blowfish simulations constants
constexpr char kBlowfishBaseAPIURL[] = "https://blowfish.wallet.hns.com";
constexpr char kBlowfishAPIVersionHeader[] = "X-Api-Version";
constexpr char kBlowfishAPIVersion[] = "2023-03-08";

constexpr int64_t kBlockTrackerDefaultTimeInSeconds = 20;
constexpr int64_t kLogTrackerDefaultTimeInSeconds = 20;

constexpr char kPolygonMainnetEndpoint[] = "https://mainnet-polygon.hns.com/";

// Unstoppable domains record key for ethereum address.
constexpr char kCryptoEthAddressKey[] = "crypto.ETH.address";
// Unstoppable domains record key for solana address.
constexpr char kCryptoSolAddressKey[] = "crypto.SOL.address";
// Unstoppable domains record key for filecoin address.
constexpr char kCryptoFilAddressKey[] = "crypto.FIL.address";

// ERC-165 identifier for ERC721 interface.
constexpr char kERC1155InterfaceId[] = "0xd9b67a26";
constexpr char kERC1155MetadataInterfaceId[] = "0x0e89341c";
constexpr char kERC721InterfaceId[] = "0x80ac58cd";
constexpr char kERC721MetadataInterfaceId[] = "0x5b5e139f";

constexpr char kBitcoinPrefKey[] = "bitcoin";
constexpr char kEthereumPrefKey[] = "ethereum";
constexpr char kFilecoinPrefKey[] = "filecoin";
constexpr char kSolanaPrefKey[] = "solana";

constexpr char kEthereumBlockTagEarliest[] = "earliest";
constexpr char kEthereumBlockTagLatest[] = "latest";

const std::string GetSardineNetworkName(const std::string& chain_id);
const base::flat_map<std::string, std::string>& GetInfuraChainEndpoints();
const base::flat_map<std::string, std::string>&
GetEthBalanceScannerContractAddresses();
bool HasJupiterFeesForTokenMint(const std::string& mint);
const std::vector<std::string>& GetEthSupportedNftInterfaces();
// Returns the URL for the Ratios service.
const std::string GetAssetRatioBaseURL();

}  // namespace hns_wallet

#endif  // HNS_COMPONENTS_HNS_WALLET_BROWSER_HNS_WALLET_CONSTANTS_H_
