/* Copyright (c) 2022 The Hns Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "hns/browser/themes/hns_private_window_theme_supplier.h"

#include "hns/browser/ui/color/hns_color_mixer.h"
#include "ui/color/color_provider_key.h"

HnsPrivateWindowThemeSupplier::HnsPrivateWindowThemeSupplier(
    bool private_window)
    : CustomThemeSupplier(ThemeType::kAutogenerated),
      for_private_window_(private_window) {}

HnsPrivateWindowThemeSupplier::~HnsPrivateWindowThemeSupplier() = default;

void HnsPrivateWindowThemeSupplier::AddColorMixers(
    ui::ColorProvider* provider,
    const ui::ColorProviderKey& key) const {
  for_private_window_ ? AddPrivateThemeColorMixer(provider, key)
                      : AddTorThemeColorMixer(provider, key);
  // Private/Tor uses same omnibox colors.
  AddHnsOmniboxPrivateThemeColorMixer(provider, key);
}
