name: Pull Request

on:
  pull_request:
    types: [opened, reopened, closed]

# Setting permissions for GITHUB_TOKEN for dependabot as default is readonly
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions?learn=dependency_version_updates&learnProduct=code-security

permissions:
  pull-requests: write

jobs:
  assign:
    name: Assign author to PR
    runs-on: ubuntu-latest
    steps:
      - name: Assign author to PR
        uses: technote-space/assign-author@v1

  # See: .github/labeler.yml
  label:
    name: Assign labels automatically
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

