[package]
name = "hns-news-cxx"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = { version = "1.0", features = [ "alloc", "std" ] }
feed-rs = { path = "../../../third_party/rust/feed_rs/v1/crate" }
log = "0.4.14"
lazy_static = "1.4.0"
regex = "1.5.5"

[lib]
name = "hns_news_cxx"
path = "lib.rs"
crate-type = ["rlib"]
